package com.ontology;

import java.util.ArrayList;
import java.util.List;

public class OntologyConstants {
	/*
	 * I thought since we aren't doing a GUI, that it might be nice to have some
	 * colours in the UI! NOTE: use RESET at the end of the string after giving
	 * it the colour.
	 */

	// Reset
	public static final String RESET = "\033[0m"; // Text Reset

	// Regular Colors
	public static final String BLACK = "\033[0;30m"; // BLACK
	public static final String RED = "\033[0;31m"; // RED
	public static final String GREEN = "\033[0;32m"; // GREEN
	public static final String YELLOW = "\033[0;33m"; // YELLOW
	public static final String BLUE = "\033[0;34m"; // BLUE
	public static final String PURPLE = "\033[0;35m"; // PURPLE
	public static final String CYAN = "\033[0;36m"; // CYAN
	public static final String WHITE = "\033[0;37m"; // WHITE

	// Bold
	public static final String BLACK_BOLD = "\033[1;30m"; // BLACK
	public static final String RED_BOLD = "\033[1;31m"; // RED
	public static final String GREEN_BOLD = "\033[1;32m"; // GREEN
	public static final String YELLOW_BOLD = "\033[1;33m"; // YELLOW
	public static final String BLUE_BOLD = "\033[1;34m"; // BLUE
	public static final String PURPLE_BOLD = "\033[1;35m"; // PURPLE
	public static final String CYAN_BOLD = "\033[1;36m"; // CYAN
	public static final String WHITE_BOLD = "\033[1;37m"; // WHITE

	// Underline
	public static final String BLACK_UNDERLINED = "\033[4;30m"; // BLACK
	public static final String RED_UNDERLINED = "\033[4;31m"; // RED
	public static final String GREEN_UNDERLINED = "\033[4;32m"; // GREEN
	public static final String YELLOW_UNDERLINED = "\033[4;33m"; // YELLOW
	public static final String BLUE_UNDERLINED = "\033[4;34m"; // BLUE
	public static final String PURPLE_UNDERLINED = "\033[4;35m"; // PURPLE
	public static final String CYAN_UNDERLINED = "\033[4;36m"; // CYAN
	public static final String WHITE_UNDERLINED = "\033[4;37m"; // WHITE

	// Background
	public static final String BLACK_BACKGROUND = "\033[40m"; // BLACK
	public static final String RED_BACKGROUND = "\033[41m"; // RED
	public static final String GREEN_BACKGROUND = "\033[42m"; // GREEN
	public static final String YELLOW_BACKGROUND = "\033[43m"; // YELLOW
	public static final String BLUE_BACKGROUND = "\033[44m"; // BLUE
	public static final String PURPLE_BACKGROUND = "\033[45m"; // PURPLE
	public static final String CYAN_BACKGROUND = "\033[46m"; // CYAN
	public static final String WHITE_BACKGROUND = "\033[47m"; // WHITE

	// High Intensity
	public static final String BLACK_BRIGHT = "\033[0;90m"; // BLACK
	public static final String RED_BRIGHT = "\033[0;91m"; // RED
	public static final String GREEN_BRIGHT = "\033[0;92m"; // GREEN
	public static final String YELLOW_BRIGHT = "\033[0;93m"; // YELLOW
	public static final String BLUE_BRIGHT = "\033[0;94m"; // BLUE
	public static final String PURPLE_BRIGHT = "\033[0;95m"; // PURPLE
	public static final String CYAN_BRIGHT = "\033[0;96m"; // CYAN
	public static final String WHITE_BRIGHT = "\033[0;97m"; // WHITE

	// Bold High Intensity
	public static final String BLACK_BOLD_BRIGHT = "\033[1;90m"; // BLACK
	public static final String RED_BOLD_BRIGHT = "\033[1;91m"; // RED
	public static final String GREEN_BOLD_BRIGHT = "\033[1;92m"; // GREEN
	public static final String YELLOW_BOLD_BRIGHT = "\033[1;93m";// YELLOW
	public static final String BLUE_BOLD_BRIGHT = "\033[1;94m"; // BLUE
	public static final String PURPLE_BOLD_BRIGHT = "\033[1;95m";// PURPLE
	public static final String CYAN_BOLD_BRIGHT = "\033[1;96m"; // CYAN
	public static final String WHITE_BOLD_BRIGHT = "\033[1;97m"; // WHITE

	// High Intensity backgrounds
	public static final String BLACK_BACKGROUND_BRIGHT = "\033[0;100m";// BLACK
	public static final String RED_BACKGROUND_BRIGHT = "\033[0;101m";// RED
	public static final String GREEN_BACKGROUND_BRIGHT = "\033[0;102m";// GREEN
	public static final String YELLOW_BACKGROUND_BRIGHT = "\033[0;103m";// YELLOW
	public static final String BLUE_BACKGROUND_BRIGHT = "\033[0;104m";// BLUE
	public static final String PURPLE_BACKGROUND_BRIGHT = "\033[0;105m"; // PURPLE
	public static final String CYAN_BACKGROUND_BRIGHT = "\033[0;106m"; // CYAN
	public static final String WHITE_BACKGROUND_BRIGHT = "\033[0;107m"; // WHITE

	public static String WELCOME_MESSAGE = "Welcome to the Crime Geolocation Ontology for Ireland";
	public static String INFO_ABOUT_ONTOLOGY = "This is an ontology spanning the Geohive Geolocation Data Ontology, "
			+ "and the 'Crimes at Garda Stations' dataset, both Irish datasets available on the web.";
	public static String PRESS_X_TO_EXIT = "Otherwise enter 'x' to exit the application.";
	public static String ERROR_READING_FILE = RED + "An error occurred when trying to load the required file." + RESET;
	public static String THANK_YOU = "Thank you for using the Crime Geolocation Ontology for Ireland!";

	// This should be used with String.format(PRESENT_USER_OPTIONS, args).
	// PRINTS IN PURPLE
	public static String PRESENT_USER_OPTIONS = "What would you like to ask? Select the number of the question to "
			+ "ask. \n\t1) %s\n\t2) %s\n\t3) %s\n\t4) %s\n\t5) %s\n\t6) %s";
	public static String OPTIONS_TO_DISPLAY_LISTS = "Enter:\n\t- 'electoral divisions' to display a list of the Irish electoral divisions\n\t- 'garda divisions' to display a list of all Garda divisions\n\t- 'crimes' to display a list of crimes for which records exist\n\t- 'counties' to display a list of all counties";
	public static String SECTION_BREAK = " - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ";

	// TODO @Amber populate these when we know what the final questions are
	public static final String FIRST_QUESTION = PURPLE_BOLD_BRIGHT + "What stations are there in a specified county?" + RESET;
	public static final String SECOND_QUESTION = PURPLE_BOLD_BRIGHT
			+ "What is the most common type of crime in a specified county in a specified year?"
			+ RESET;
	public static final String THIRD_QUESTION = PURPLE_BOLD_BRIGHT + "What electoral divisions are in a specified garda division?"
			+ RESET;
	public static final String FOURTH_QUESTION = PURPLE_BOLD_BRIGHT
			+ "What are the crimes of which instances in a specified county were over a specified threshold?";
	public static final String FIFTH_QUESTION = PURPLE_BOLD_BRIGHT
			+ "Which county saw the biggest rise in a specific crime over the period 2004-2016?" + RESET;
	public static final String SIXTH_QUESTION = PURPLE_BOLD_BRIGHT
			+ "Which Electoral Division had the lowest number of a specific crime in a given year?" + RESET;

	public static List<String> ALL_CRIMES = new ArrayList<String>() {
		{
			add("Attempts or Threats to Murder, Assaults, Harassments and Related Offences");
			add("Burglary and Related Offences");
			add("Controlled Drug Offences");
			add("Damage to Property and to the Environment");
			add("Dangerous or Negligent Acts");
			add("Fraud, Deception and Related Offences");
			add("Kidnapping and Related Offences");
			add("Offences against Government, Justice Procedures and Organisation of Crime");
			add("Public Order and other Social Code Offences");
			add("Robbery, Extortion and Hijacking Offences");
			add("Theft and Related Offences");
			add("Weapons and Explosives Offences");
		}
	};

	public static void printAllCrimes() {
		System.out.println(
				GREEN_BOLD + "The crimes you can select for questions 5 and 6 (easiest to just copy+paste): " + RESET);
		for (String crime : ALL_CRIMES) {
			System.out.println("\t" + crime);
		}
	}

	public static List<String> ALL_COUNTIES = new ArrayList<String>() {
		{
			add("Carlow");
			add("Cavan");
			add("Clare");
			add("Cork");
			add("Donegal");
			add("Dublin");
			add("Galway");
			add("Kerry");
			add("Kildare");
			add("Kilkenny");
			add("Laois");
			add("Leitrim");
			add("Limerick");
			add("Longford");
			add("Louth");
			add("Mayo");
			add("Meath");
			add("Monaghan");
			add("Offaly");
			add("Roscommon");
			add("Sligo");
			add("Tipperary");
			add("Waterford");
			add("Westmeath");
			add("Wexford");
			add("Wicklow");
		}
	};

	public static void printAllCounties() {
		System.out.println(GREEN_BOLD + "The counties you can select (easiest to just copy+paste): " + RESET);
		for (String county : ALL_COUNTIES) {
			System.out.println("\t" + RESET + county );
		}
	}

	public static List<String> ALL_DIVISIONS = new ArrayList<String>() {
		{
			add("Cavan/Monaghan Division");
			add("Clare Division");
			add("Cork City Division");
			add("Cork North Division");
			add("Cork West Division");
			add("D.M.R. Eastern Division");
			add("D.M.R. North Central Division");
			add("D.M.R. Northern Division");
			add("D.M.R. South Central Division");
			add("D.M.R. Southern Division");
			add("D.M.R. Western Division");
			add("Donegal Division");
			add("Galway Division");
			add("Kerry Division");
			add("Kildare Division");
			add("Kilkenny/Carlow Division");
			add("Laois/Offaly Division");
			add("Limerick Division");
			add("Louth Division");
			add("Mayo Division");
			add("Meath Division");
			add("Roscommon/Longford Division");
			add("Sligo/Leitrim Division");
			add("Tipperary Division");
			add("Waterford Division");
			add("Westmeath Division");
			add("Wexford Division");
			add("Wicklow Division");
		}
	};

	public static List<String> ALL_ELECTORAL_DIVISIONS = new ArrayList<String>() {
		{
			add("Ballybrack");
			add("Ballyhorgan");
			add("Tallaght-Glenview");
			add("Kilcummer");
			add("Cappalough");
			add("Kilmacumsy");
			add("Johnstown");
			add("St. Patrick's A");
			add("Cnoc na Lobhar");
			add("Trienearagh");
			add("Skerries");
			add("Woodstown");
			add("Ballynacourty");
			add("Derrycooley");
			add("Athleague West");
			add("Derrynagittagh");
			add("Carna");
			add("Cliffony North");
			add("Gunsborough");
			add("Leitir MÃƒÂ³ir");
			add("Moycarky");
			add("Castlemartyr");
			add("Glenealy");
			add("Cabra West C");
			add("Drumreilly South");
			add("Clogrenan");
			add("Ballyea");
			add("Cappalusk");
			add("Portroyal");
			add("Cloncagh");
			add("Rath");
			add("Kyle");
			add("Blanchardstown-Blakestown");
			add("Moybolgue");
			add("Wexford No. 1 Urban");
			add("Ardmalin");
			add("Ballynapark");
			add("Knockatooan");
			add("Knockmahon");
			add("Aughwilliam");
			add("Priorswood A");
			add("Ballybroder");
			add("Grange South");
			add("Castleforward");
			add("Lackan");
			add("Magorban");
			add("Lugglass");
			add("Caldragh");
			add("Meelick");
			add("Ballyshear");
			add("Larah North");
			add("Boston");
			add("Sliabh an Aonaigh");
			add("Narraghmore");
			add("Clonmacnoise");
			add("Ballysadare West");
			add("Ballyfeard");
			add("Inch");
			add("Knockanbaun");
			add("Caherconlish West");
			add("Freshford");
			add("Tobernea");
			add("Killucan");
			add("Killymasny");
			add("Ballykisteen");
			add("Bredagh");
			add("Castletown");
			add("Finglas South A");
			add("Dundalk Urban No. 2");
			add("An Uillinn");
			add("Bulgaden");
			add("Ballynashee");
			add("Cloghan");
			add("Malin");
			add("Ballyheeny");
			add("Donard");
			add("Cloghermore");
			add("Borrisnafarney");
			add("Broughal");
			add("Royal Exchange A");
			add("Clonfert West");
			add("Dunleer");
			add("Iveruss");
			add("Convoy");
			add("Moatfarrell");
			add("Buckill");
			add("Athlone East Urban");
			add("Ballyovey");
			add("Swords-Glasmore");
			add("Midleton Rural");
			add("Nenagh East Urban");
			add("Dunfanaghy");
			add("Blackrock-Seapoint");
			add("Ballyshannon Rural");
			add("Maigh Cuilinn");
			add("Navan Urban");
			add("Sligo North");
			add("Nantinan");
			add("Coole");
			add("Ballingurteen");
			add("Portmagee");
			add("Ballinalee");
			add("Drummully");
			add("Gurranebraher C");
			add("Drumhillagh");
			add("Cloncurry");
			add("Killarga");
			add("Ballyclogh");
			add("Seacor");
			add("Youghalarra");
			add("Cill MaoilchÃƒÂ©adair");
			add("Crosagstown");
			add("Arran Quay A");
			add("Taghboy");
			add("Turners Cross C");
			add("Castlebanny");
			add("Doonbally");
			add("Kilmoylan");
			add("Ceann Droma");
			add("Arklow No. 1 Urban");
			add("Tawnynagry");
			add("Mounterin");
			add("Ushers E");
			add("Killinkere");
			add("Carrignavar");
			add("Derryglassaun");
			add("Colmanswell");
			add("Glasheen A");
			add("Louisburgh");
			add("St. Helen's");
			add("Knockantota");
			add("Castlebar Urban");
			add("Beaumont C");
			add("Tullig");
			add("An Fhairche");
			add("Cloonfower");
			add("Kilfearagh");
			add("Cabra East A");
			add("Louth");
			add("Breaghwy");
			add("Rathclooney");
			add("Mealagh");
			add("Bilboa");
			add("Grange North");
			add("Dunganstown West");
			add("Rathmines East C");
			add("Gorey Rural");
			add("Kilsallagh");
			add("Golden");
			add("St. Patrick's B");
			add("Kilmore");
			add("Kylemore");
			add("Greystones");
			add("Dundalk Urban No. 4");
			add("Lucan Heights");
			add("Ballybaan");
			add("Knockarrow");
			add("Grallagh");
			add("Castleventry");
			add("Fews");
			add("Kilrush Rural");
			add("Dysartgallen");
			add("Mountplummer");
			add("Montenotte A");
			add("Bracknagh");
			add("Askeaton East");
			add("Bert");
			add("Drumgort");
			add("Kiltoom");
			add("Clonmoyle");
			add("Emo");
			add("Derrygrath");
			add("Timahoe North");
			add("Johnstown");
			add("Streamhill");
			add("Feenagh");
			add("Gartan");
			add("Brewsterfield");
			add("Moneymore");
			add("Clontarf West C");
			add("Thomastown");
			add("Castle B");
			add("Clones Rural");
			add("Ballinlough");
			add("Mohernagh");
			add("Three Trees");
			add("Fontstown");
			add("Farranshone");
			add("Conga");
			add("Dunmore");
			add("Inchicore B");
			add("Toocananagh");
			add("Coolclogh");
			add("Lady's Island");
			add("Kilkea");
			add("Owennadornaun/Bundorragha");
			add("Dolla");
			add("Ballysheehan");
			add("Shancough");
			add("Dunamaggan");
			add("Kilcoona");
			add("Baurtregaum");
			add("Donegal");
			add("Portmarnock South");
			add("Castlequin");
			add("Ballycallan");
			add("Meencargagh");
			add("Salthill");
			add("Inistioge");
			add("Croghan");
			add("Kilmurry");
			add("Ballinlough A");
			add("CrÃƒÂ³ Bheithe");
			add("Drumcondra South C");
			add("Killeagh");
			add("Ardagh West");
			add("Newbliss");
			add("Bannow");
			add("Bellatrain");
			add("Cattan");
			add("Sonnagh");
			add("Fennor");
			add("Rathmore");
			add("Tallaght-Belgard");
			add("Gortroe");
			add("Meelick");
			add("Killukin");
			add("Abbey");
			add("Drumacoo");
			add("Lucan North");
			add("Ballinderry");
			add("Clogheen");
			add("Ballycanew");
			add("Annaghmore");
			add("Cappaghabaun");
			add("Chapelizod");
			add("Ennismore");
			add("Loughmoe");
			add("An Chorr");
			add("Monanimy");
			add("Kilnamona");
			add("Pouladuff B");
			add("Mansion House B");
			add("Burton Hall");
			add("Turners Cross B");
			add("Na Forbacha");
			add("Kilnarath");
			add("Artramon");
			add("Coonogue");
			add("Balscadden");
			add("Castleboy");
			add("Banada");
			add("New Ross Urban");
			add("Clondagad");
			add("Ross");
			add("Kilcowan");
			add("North Dock C");
			add("Glencar");
			add("Drumgurra");
			add("Ardnaglew");
			add("Ticor South");
			add("Kilpatrick");
			add("Wormhole");
			add("Illies");
			add("Togher");
			add("Monasterevin");
			add("Haggardstown");
			add("Lisconny");
			add("Rathcormack");
			add("Fethard");
			add("Kilmallock");
			add("Dunbell");
			add("Lisselton");
			add("Kilcumny");
			add("Tieveskeelta");
			add("Georgestown");
			add("Clondrohid");
			add("Mount Eagle");
			add("Finglas North B");
			add("West Gate");
			add("Clogher");
			add("Ballyseedy");
			add("Doonloughan");
			add("Ballyanne");
			add("Crownarad");
			add("Killoteran");
			add("Teeranearagh");
			add("Beal");
			add("Burgage");
			add("Caltragh");
			add("Summerhill");
			add("Tallaght-Jobstown");
			add("Roosky");
			add("Dunmanway North");
			add("Firry/Newgrove");
			add("Kilmore");
			add("Deel");
			add("Ballyspillane");
			add("Mountmellick Urban");
			add("Rosmoylan");
			add("Bree");
			add("Cong");
			add("Tullynaught");
			add("Sutton");
			add("An ClochÃƒÂ¡n");
			add("Ballygarden");
			add("Terryglass");
			add("Blackrock-Monkstown");
			add("Liscananaun");
			add("St. Mary's");
			add("Kingscourt");
			add("Ballyhack");
			add("Garrangibbon");
			add("Termon");
			add("North Dock A");
			add("Clonmult");
			add("Doocastle");
			add("Gurranebraher A");
			add("Carbury");
			add("Drumahaire");
			add("Cill ChuÃƒÂ¡in");
			add("Carndonagh");
			add("Ballymurreen");
			add("Baldoyle");
			add("Creeve");
			add("Marley");
			add("Ballygroman");
			add("Rosbercon Rural");
			add("Beaghmore");
			add("Kilmacdonogh");
			add("DÃƒÂºn Laoghaire-West Central");
			add("Ballymitty");
			add("Rossinver East");
			add("Priorswood B");
			add("Cullen");
			add("Tiaquin");
			add("Nohaval");
			add("Gillabbey B");
			add("Dunmurry");
			add("Whitemoor");
			add("Ballynakill");
			add("Castletown");
			add("Cloonkeen");
			add("Beaumont A");
			add("Skibbereen Urban");
			add("Ravensdale");
			add("Toormore");
			add("Tintern");
			add("Botanic B");
			add("Castletown");
			add("Ballynagoraher");
			add("Scarriff");
			add("Kilmonoge");
			add("Kinnegad");
			add("Ferrybank");
			add("Adrigole");
			add("Rathmines East A");
			add("Matehy");
			add("Brackloon");
			add("Tubbrid");
			add("Liscannor");
			add("Inishbofin");
			add("Clashmore");
			add("Rathroe");
			add("Mountdavis");
			add("Firhouse Village");
			add("Killallaghtan");
			add("Ballymorin");
			add("Grange");
			add("Macroom Urban");
			add("Shinrone");
			add("Ballycannan");
			add("Moyne");
			add("Garryduff");
			add("Killulagh");
			add("Cappagh");
			add("Mardyke");
			add("Trim Urban");
			add("Pallaskenry");
			add("Ballyshannon");
			add("Colt");
			add("Scotstown");
			add("Umma");
			add("Athenry");
			add("Ballynamona");
			add("Castlebellingham");
			add("Kilrush");
			add("Rathmore");
			add("Scartaglin");
			add("Meathas Truim");
			add("Taghmaconnell");
			add("Caherelly");
			add("Ardpatrick");
			add("Ballinamuck West");
			add("Clontarf West A");
			add("Powerstown");
			add("Aghabog");
			add("Ballymacwilliam");
			add("Ballynanty");
			add("Bricklieve");
			add("Knockaderry");
			add("Dundrum-Kilmacud");
			add("Camas");
			add("Kilfinnane");
			add("Donaghmore");
			add("Drumfinn");
			add("Achonry West");
			add("Knockmourne");
			add("Newport East");
			add("Ballyheige");
			add("Killea");
			add("Callan Urban");
			add("Westport Urban");
			add("Ballynoe");
			add("Tullyvin West");
			add("Malahide West");
			add("Caherdaniel");
			add("Templevanny");
			add("Cabra East B");
			add("Cranford");
			add("Goresbridge");
			add("Castlebar Rural");
			add("Abbey D");
			add("Rossroe");
			add("Glenalla");
			add("Drumcondra South A");
			add("Dromdaleague North");
			add("Churchtown-Woodlawn");
			add("Currin");
			add("Ennereilly");
			add("Rathmines East D");
			add("Ballybay Rural");
			add("Coolmountain");
			add("Ballyhowly");
			add("Kilfeakle");
			add("Molahiffe");
			add("St. Patrick's C");
			add("Ushers C");
			add("Kilcullen");
			add("Strade");
			add("Oldtown");
			add("Lucan-St. Helen's");
			add("Castlecove");
			add("Swanlinbar");
			add("Clonakilty Rural");
			add("Ballylehane");
			add("Kilsallaghan");
			add("Dunbeacon");
			add("Abbey West");
			add("Kilkenny Rural");
			add("The Leap");
			add("Termonbarry");
			add("Knock");
			add("Kilmacomma");
			add("Duagh");
			add("Rinn");
			add("Ballyallinan");
			add("Cannaway");
			add("Ballycullen");
			add("Montenotte B");
			add("Clonmore");
			add("Tramore C");
			add("Tullaghorton");
			add("Gowel");
			add("Talbotstown");
			add("Arless");
			add("Addergoole");
			add("Woodland");
			add("Milane");
			add("Peppardstown");
			add("Crosskeys");
			add("Rathbeagh");
			add("Cloonclare");
			add("Knocknascrow");
			add("Riverdale");
			add("The Glen");
			add("Ballybeg");
			add("Graney");
			add("Tedavnet");
			add("Cootehill Urban");
			add("Knockdrin");
			add("Coumaraglin");
			add("Mayglass");
			add("Kilrush");
			add("Cullenwaine");
			add("Easky East");
			add("Emper");
			add("Butlerstown");
			add("Kilteel");
			add("Blennerville");
			add("Kilmaloda East");
			add("Ballynakill");
			add("Clara");
			add("Goleen");
			add("Rathconrath");
			add("Mulmosog");
			add("Comeragh");
			add("Ballinacor");
			add("Laherne");
			add("Lackabaun");
			add("Edenmore");
			add("Fair Gate");
			add("St. Tierney");
			add("Ballinastack");
			add("Arabela");
			add("Kiltealy");
			add("Clonleigh South");
			add("Doogary");
			add("Dromdaleague South");
			add("Stillorgan-Mount Merrion");
			add("Ballyegan");
			add("Ballydangan");
			add("Rathmolyon");
			add("Kilbride North");
			add("Tallaght-Fettercairn");
			add("Kilcor");
			add("Mountmellick Rural");
			add("Killummod");
			add("Ryehill");
			add("Tarmon");
			add("Kells");
			add("Wallstown");
			add("Leitrim");
			add("Castle");
			add("Lough Eask");
			add("Lusk");
			add("Dromana");
			add("Frenchpark");
			add("Loghill");
			add("Cherry Orchard A");
			add("Carrickbanagher");
			add("Killoe");
			add("Clydagh");
			add("Temple");
			add("Gullane");
			add("Wingfield");
			add("Castleshane");
			add("Mountjoy B");
			add("Cullen");
			add("Islandeady");
			add("Cabra West B");
			add("Killofin");
			add("Rathcooney");
			add("Drumreilly North");
			add("St. Patrick's");
			add("Cross Roads");
			add("Ballagh");
			add("Balbriggan Rural");
			add("Cloonburren");
			add("Glynn");
			add("Kilchreest");
			add("Blanchardstown-Abbotstown");
			add("Caragh");
			add("Ballinduff");
			add("Kilmeen");
			add("DÃƒÂºn Laoghaire-Sandycove");
			add("Eyre Square");
			add("Humewood");
			add("Phoenix Park");
			add("Glencar");
			add("Killadysert");
			add("Tullagh");
			add("Newtown");
			add("Farranferris C");
			add("Leixlip");
			add("An Cheapaigh Dhuibh");
			add("Kilscoran");
			add("Abbeyville");
			add("St. Mary's");
			add("Sailearna");
			add("Ballymun E");
			add("Mallow South Urban");
			add("Jenkinstown");
			add("Balla");
			add("Horetown");
			add("Cremartin");
			add("Kilcomb");
			add("Kilteely");
			add("Corlea/Cahermurphy");
			add("Killare");
			add("Ballygriffin");
			add("Dunamon");
			add("Oldcourt");
			add("Errislannan");
			add("Banna");
			add("Barronstown");
			add("Kilmacleague");
			add("Garryhill");
			add("Kilcoole");
			add("Donaghmore");
			add("Lough Allen/Altagowlan");
			add("Knocklough");
			add("Abbey East");
			add("Dunganstown East");
			add("Derry");
			add("St. Mary's");
			add("Tantallon");
			add("Knockavilly");
			add("Drummeel");
			add("Tullamore Rural");
			add("Ballinrobe");
			add("Carrigcastle");
			add("Grean");
			add("Bellanalack");
			add("Ros Goill");
			add("Ballybacon");
			add("Mahon B");
			add("Ceanannas MÃƒÂ³r (Kells) Urban");
			add("Boherquill");
			add("Newtown");
			add("Aille");
			add("North Dock B");
			add("Abbeylara");
			add("Kilbeagh");
			add("Cappancur");
			add("Stradone");
			add("Stradbally");
			add("Cinn Aird");
			add("Drom");
			add("Balgriffin");
			add("Kilbrin");
			add("Creevy");
			add("Rockhill");
			add("An Geata MÃƒÂ³r Theas");
			add("Youghal Rural");
			add("Foxrock-Beechpark");
			add("Na hUlÃƒÂ¡in");
			add("Pontoon");
			add("Kilbrew");
			add("Rossinver West");
			add("Carrick-on-Suir Urban");
			add("Dalkey Upper");
			add("Cooloo");
			add("O'Brennan");
			add("Arderin");
			add("Ballymote");
			add("Gillabbey C");
			add("Feighcullen");
			add("Templebreedy");
			add("Knappagh");
			add("Meelick");
			add("Moyne");
			add("Burnchurch");
			add("Ballina Urban");
			add("An Daingean");
			add("Granard Rural");
			add("Beaumont B");
			add("Goland");
			add("Youghal Urban");
			add("Ardagh");
			add("Bellanagare");
			add("Botanic C");
			add("Aghagower South");
			add("Famma");
			add("Bellavary");
			add("Castleisland");
			add("Shannonharbour");
			add("Ballyblood");
			add("Clonkeen");
			add("Fanad North");
			add("Glanlough");
			add("Churchtown-Nutgrove");
			add("Killeenavarra");
			add("Dunloe");
			add("Rathmines East B");
			add("Aghanagh");
			add("Glanworth West");
			add("Kilmeena");
			add("Glengar");
			add("Doocarrig");
			add("Fair Hill A");
			add("Templederry");
			add("Droichead Nua (Newbridge) Urban");
			add("Rowan");
			add("Enniskerry");
			add("Buncrana Urban");
			add("Lucan-Esker");
			add("Templemichael");
			add("Banawn");
			add("Greethill");
			add("Cahermore");
			add("Newcastle");
			add("Templeharry");
			add("Gowran");
			add("Oughteragh");
			add("Ballyglass");
			add("Dromore");
			add("Imael North");
			add("Banteer");
			add("Cashel");
			add("Carriglea");
			add("Mayfield");
			add("Taghmon");
			add("Killooly");
			add("Killeany");
			add("Raheen");
			add("Dromiskin");
			add("Portumna");
			add("Clara");
			add("Newgrove");
			add("Mountrivers");
			add("Cappamore");
			add("Kilmainham");
			add("Moneenalassa");
			add("Clonbrock");
			add("Kilbeheny");
			add("Mount Temple");
			add("Castle A");
			add("Mahoonagh");
			add("Ballyhooly");
			add("Dundrum-Sandyford");
			add("Shanmullagh");
			add("Donore");
			add("Swineford");
			add("Kilwatermoy East");
			add("Templeludigan");
			add("Knocknagashel");
			add("Rathnaveoge");
			add("Kilshalvy");
			add("Owel");
			add("Coolaghmore");
			add("Rockfield");
			add("Corkermore");
			add("Whitechurch");
			add("Knock");
			add("Ferns");
			add("Graiguenamanagh");
			add("Killahan");
			add("Ardara");
			add("Drumcondra South B");
			add("Clonskeagh-Belfield");
			add("Kilmore");
			add("Ballyhaise");
			add("Ballybay Urban");
			add("Drinagh");
			add("Stillorgan-Leopardstown");
			add("Muckross");
			add("Monasteroris");
			add("Tumna North");
			add("Saggart");
			add("Castle Hyde");
			add("Kildare");
			add("Ightermurragh");
			add("Turlough");
			add("Dawros");
			add("Tullahought");
			add("Limerick North Rural");
			add("Drumraney");
			add("Inver");
			add("Kinsaley");
			add("Kilkieran");
			add("Dunmanus");
			add("Listowel Rural");
			add("Coolougher");
			add("Whitehall D");
			add("Kilronan");
			add("Tankardstown");
			add("Clones Urban");
			add("Dromin");
			add("Kilfeighny");
			add("Muckanagh");
			add("Rakenny");
			add("Kilmore D");
			add("Cleanrath");
			add("Ballygrennan");
			add("Drumboory");
			add("Mansion House A");
			add("Greenane");
			add("Boyle Urban");
			add("Gubacreeny");
			add("Turners Cross A");
			add("Terenure-St. James");
			add("Kilmovee");
			add("Ballyboghil");
			add("Curraghmore");
			add("Aghadoe");
			add("Crossbane");
			add("Teerelton");
			add("DÃƒÂºn Laoghaire-Sallynoggin South");
			add("Monasterboice");
			add("Claddagh");
			add("Kilbride");
			add("Kilnaleck");
			add("Drumreilly West/Drumreilly East");
			add("Myross");
			add("Farranferris A");
			add("Donaghcumper");
			add("Monamolin");
			add("Gleann na Muaidhe");
			add("Mount Sion");
			add("Corr");
			add("Ballymun C");
			add("Loughea");
			add("Gorteen");
			add("Killeely");
			add("Enniscoffey");
			add("Bunowen");
			add("Kilbeggan");
			add("Kilcoe");
			add("Evergreen");
			add("Russellstown");
			add("Ballinderry");
			add("Gardenmorris");
			add("Rathborney");
			add("Ballymoe");
			add("Ardfert");
			add("Barrack Village");
			add("Killea");
			add("Cranemore");
			add("Ballynamona");
			add("Rathmore");
			add("Kilbride South");
			add("Clareabbey");
			add("Crossmolina South");
			add("Moylagh");
			add("Killinagh/Teebane");
			add("Carnagarve");
			add("Castlelost");
			add("Templecarn");
			add("Ardfinnan");
			add("Riverstown");
			add("Templepatrick");
			add("Greenfort");
			add("Lackan");
			add("Adamstown");
			add("North City");
			add("Clones");
			add("Rahasane");
			add("Foxhall");
			add("Kilmaclasser");
			add("Greenmount");
			add("St. Mary's");
			add("Cavangarden");
			add("Bealanageary");
			add("Burt");
			add("Balbriggan Urban");
			add("Kilkerranmore");
			add("Ullid");
			add("Enagh");
			add("Shrule");
			add("The Glen B");
			add("Coom");
			add("DÃƒÂºn Laoghaire-Salthill");
			add("Ballintemple");
			add("Ballybricken West");
			add("Ballyconnell");
			add("Kilmacowen");
			add("Tipperary West Urban");
			add("Coolmain");
			add("Gowlane");
			add("Dalkey-Coliemore");
			add("Dunmore South");
			add("Timogue");
			add("Tagheen");
			add("Gillabbey A");
			add("Harristown");
			add("Claretuam");
			add("Killinane");
			add("Roscrea");
			add("Carrigboy");
			add("Kilkenny No. 1 Urban");
			add("Ballinvoher");
			add("Drumdoo");
			add("Errill");
			add("Ballymun F");
			add("Church Hill");
			add("Midleton Urban");
			add("Drumod");
			add("Skull");
			add("Botanic A");
			add("Danesfort");
			add("Figullar");
			add("Posseckstown");
			add("Bruff");
			add("Drumcarban");
			add("Farranbrien");
			add("Glenboy");
			add("Templemaley");
			add("Rathfarnham");
			add("Lissonuffy");
			add("Kilpatrick");
			add("Bohola");
			add("Coolies");
			add("Downings");
			add("Corriga");
			add("Old Ross");
			add("Firhouse-Knocklyon");
			add("Loughdawan");
			add("Tramore");
			add("Springfort");
			add("Tankardstown");
			add("Baurleigh");
			add("Ettagh");
			add("Tullaroan");
			add("Creeslough");
			add("Tuam Rural");
			add("Clooncoorha");
			add("Clenor");
			add("Kilcoran");
			add("Furroor");
			add("Merchants Quay C");
			add("Bawncross");
			add("Killua");
			add("Tinnasaggart");
			add("Mahon C");
			add("Craughwell");
			add("Kilbride");
			add("Crinnaloo");
			add("Tubbrit");
			add("Tullokyne");
			add("Duncormick");
			add("Cappard");
			add("Portloman");
			add("Ballyvaskin");
			add("Mount Falcon");
			add("Creggan Upper");
			add("Ballinamuck East");
			add("Cill ChuimÃƒÂ­n");
			add("Birdhill");
			add("Killinure");
			add("Clonmel West Urban");
			add("Edermine");
			add("Dundrum-Balally");
			add("Graigue Urban");
			add("Clonmacduff");
			add("Achonry East");
			add("Caher");
			add("Clonleigh");
			add("Cullenagh");
			add("Monsea");
			add("Ballynagore");
			add("Callan Rural");
			add("Ballynabanoge");
			add("Killygordon");
			add("Kilmucklin");
			add("Aghaboy");
			add("Mertonhall");
			add("Killag");
			add("Freaghana");
			add("Clogherbrien");
			add("Rosnakill");
			add("Clontarf West E");
			add("Churchtown-Orwell");
			add("Killinny");
			add("Clonmore");
			add("Oola");
			add("Gortnaskehy");
			add("Stillorgan-Deerpark");
			add("Milltown");
			add("Ushers B");
			add("Rushfield");
			add("Gilltown");
			add("Carrig");
			add("Ardnaree South Urban");
			add("Ceann TrÃƒÂ¡");
			add("Annestown");
			add("Cappagh");
			add("Templeorum");
			add("Lettermore");
			add("Castleknock-Knockmaroon");
			add("Crookhaven");
			add("Nuns Island");
			add("Grange");
			add("Aghacashel");
			add("Killehenny");
			add("Whitehall B");
			add("Gurteen");
			add("Rathpatrick");
			add("Carrickmacross Urban");
			add("Drommartin");
			add("Knappagh");
			add("Killanummery");
			add("Ardskeagh");
			add("John's C");
			add("Drum");
			add("Kimmage E");
			add("Glenlara");
			add("Elphin");
			add("Ballyellin");
			add("Tramore B");
			add("Killeen");
			add("Srahmore");
			add("Holmpatrick");
			add("Tiranascragh");
			add("Sneem");
			add("Clonygowan");
			add("Drumcolumb");
			add("Lehenagh");
			add("Clontarf East D");
			add("Kilskeer");
			add("Kiltormer");
			add("Drumrat");
			add("Ballynacally");
			add("Cloverhill");
			add("Kilglass");
			add("Carrigbaun");
			add("Kinturk");
			add("Crumlin F");
			add("Fair Hill B");
			add("Ballyhoolahan");
			add("Barr RÃƒÂºscaÃƒÂ­");
			add("Morrisson's Avenue West");
			add("Sheskin");
			add("Dangan");
			add("Colligan");
			add("Ballymun A");
			add("Tallaght-Avonbeg");
			add("Fahymore");
			add("Cangort");
			add("Ardagh");
			add("Dysart");
			add("Ballynakill");
			add("Allow");
			add("Kilbarrymeaden");
			add("Renmore");
			add("Fore East");
			add("Coolagh");
			add("City Hall B");
			add("Rahugh");
			add("Buolick");
			add("Kilbora");
			add("Derrew");
			add("Cronelea");
			add("Killaan");
			add("Rathea");
			add("Ballykilmore");
			add("Diamond");
			add("Stillorgan-Merville");
			add("Clonegall");
			add("Ballincor");
			add("Fuerty");
			add("Kilcummin");
			add("Tomhaggard");
			add("Carrowmore");
			add("Stabannan");
			add("Magheraboy");
			add("Faughalstown");
			add("Earlstown");
			add("Templemary");
			add("Carrick");
			add("Laghy");
			add("Kilcash");
			add("Clonmel East Urban");
			add("Rathcor");
			add("Askeaton West");
			add("Bellanode");
			add("Ballyarthur");
			add("Sonnagh");
			add("Churchtown");
			add("Killann");
			add("Mountjoy A");
			add("Redhill");
			add("Coolaney");
			add("Rosenallis");
			add("Drumcarrow");
			add("Kilmessan");
			add("Kilseily");
			add("Lismore Urban");
			add("Loughkeel");
			add("Ovens");
			add("Stratford");
			add("Kinlough");
			add("Airport");
			add("Drumcliff East");
			add("Dunderrow");
			add("Farnans");
			add("Kiltamagh");
			add("Kilcooly");
			add("Lackan North");
			add("Magherareagh");
			add("Killeenasteena");
			add("Aglish");
			add("DÃƒÂºn Laoghaire-Sallynoggin West");
			add("Killashandra");
			add("Dangan");
			add("Modeshil");
			add("Athboy");
			add("Lurgan");
			add("Castletown");
			add("Grange C");
			add("Kilfiddane");
			add("Shortcourse");
			add("Skibbereen Rural");
			add("Lisgillock");
			add("Blandsfort");
			add("Killynenagh");
			add("Farranferris B");
			add("Cill Charthaigh");
			add("Kilcock");
			add("Burriscarra");
			add("Caher");
			add("Drangan");
			add("Riverstown");
			add("Tallaght-Oldbawn");
			add("Argideen");
			add("Cnoc an Daimh");
			add("Turra");
			add("Ballymun D");
			add("Caraun");
			add("Mallow North Urban");
			add("Addergoole");
			add("Kilgarrylander");
			add("Ballinteer-Ludford");
			add("Kinure");
			add("Lisgarve/Mantua");
			add("Huntingtown");
			add("Mullary");
			add("Cams");
			add("Coolreagh");
			add("Ballaghameehan");
			add("Crusheen");
			add("Kilpeacon");
			add("Derragh");
			add("Drumdaff");
			add("New Ross Rural");
			add("Drumkeeran");
			add("Fennagh");
			add("Newmarket");
			add("Cobh Urban");
			add("Tynagh");
			add("Clenagh");
			add("Shangarry");
			add("Mellifont");
			add("Pettigoe");
			add("Movode");
			add("Ballymurphy");
			add("Rosnalee");
			add("Bohadoon");
			add("Doora");
			add("Merchants Quay A");
			add("Winetown");
			add("Millford");
			add("Graignagower");
			add("Blackpool B");
			add("Skehanagh");
			add("Kilcloher");
			add("Ledwithstown");
			add("Moat");
			add("The Harrow");
			add("Springfield");
			add("An SpidÃƒÂ©al");
			add("Cruicetown");
			add("Ballynacourty");
			add("Kanturk");
			add("Ballinadee");
			add("Luggacurren");
			add("An Geata MÃƒÂ³r Thuaidh");
			add("Letter");
			add("Castle Talbot");
			add("Kinvarra");
			add("Mountkennedy");
			add("An Sliabh Riabhach");
			add("Ferbane");
			add("Carrick-on-Suir Rural");
			add("Middleton");
			add("Dalkey Hill");
			add("Vicarstown");
			add("Ballintogher West");
			add("Newtownbarry");
			add("Oranmore");
			add("Deelis");
			add("Cuffsborough");
			add("Crossboyne");
			add("Timoney");
			add("Ballyellis");
			add("Kilkenny No. 2 Urban");
			add("Kyle");
			add("An Baile Dubh");
			add("Letterbrick");
			add("Inch Island");
			add("O'More's Forest");
			add("Aghagower North");
			add("Kilmaine");
			add("Killesk");
			add("Ennisnag");
			add("Bruree");
			add("Staholmog");
			add("Abington");
			add("Kiltybegs");
			add("Churchtown-Landscape");
			add("Keeldra");
			add("Ballybrophy");
			add("Mote");
			add("Ardcrony");
			add("Glanworth East");
			add("Currans");
			add("Graigue");
			add("Shercock");
			add("Killuran");
			add("Droichead Nua (Newbridge) Rural");
			add("Kiltyclogher");
			add("An Mhin Aird");
			add("Scrabby");
			add("Killavinoge");
			add("Keale");
			add("Ballymoon");
			add("Figart");
			add("Bengour");
			add("Leitrim");
			add("Aghaviller");
			add("Tuam Urban");
			add("Ardagh");
			add("Rotunda B");
			add("Doneraile");
			add("Blackrock-Glenomena");
			add("Cuildoo");
			add("Killanniv");
			add("Merchants Quay D");
			add("Killygarvan");
			add("Knocktemple");
			add("Carrigallen West");
			add("John's A");
			add("Kiltartan");
			add("Kimmage C");
			add("Courtmacsherry");
			add("Carragh");
			add("Inch");
			add("Creeve");
			add("Tacumshin");
			add("Kilfaughnabeg");
			add("Garadice");
			add("Donaghpatrick");
			add("Garristown");
			add("Listerlin");
			add("Castletaylor");
			add("Loughbrin");
			add("Raharney");
			add("Killarney Rural");
			add("Kiltullagh");
			add("Cloonadrum");
			add("Clontarf East B");
			add("Ratoath");
			add("Murneen");
			add("Cloonanaha");
			add("Burgesbeg");
			add("Castleffrench");
			add("Liscleary");
			add("Moate");
			add("Ballyagran");
			add("Ballyboden");
			add("Aghern");
			add("Ballinlough");
			add("Bruis");
			add("Ballintemple");
			add("Feakle");
			add("Croagh");
			add("Rochestown");
			add("Clonkeen");
			add("Rathfarnham-St. Enda's");
			add("Clarinbridge");
			add("Tumgesh");
			add("Belvidere");
			add("Grange");
			add("Curryglass");
			add("Fox's Castle");
			add("Ballycommon");
			add("Ardagh East");
			add("Rathcabban");
			add("Enniscorthy Rural");
			add("Lauree");
			add("Newcastle");
			add("Trohanny");
			add("Ballintemple");
			add("Templebredon");
			add("Stillorgan-Kilmacud");
			add("Aghancon");
			add("Tivannagh");
			add("Ardnagragh");
			add("Castlecooke");
			add("Newcastle");
			add("Ardea");
			add("Coolamber");
			add("Ballylaneen");
			add("Tubbrid");
			add("Singland B");
			add("Coolgreany");
			add("Haugh");
			add("Cloneen");
			add("Killury");
			add("Cloondara");
			add("Whitehall C");
			add("Stradbally");
			add("Castleblayney Urban");
			add("Darragh");
			add("Moydrum");
			add("Ballyshannon Urban");
			add("Beagh");
			add("Killeely A");
			add("Donaghmoyne");
			add("Drumcondra");
			add("Mullagh");
			add("Kylemore");
			add("Gortmore");
			add("Boyle Rural");
			add("Moyne");
			add("Lecarrow");
			add("Cloonteen");
			add("Lea");
			add("Rathmelton");
			add("Howth");
			add("Tahilla");
			add("Lissadill West");
			add("Clontarf East E");
			add("Raphoe");
			add("Castlegar");
			add("Kilfree");
			add("Causeway");
			add("Killea");
			add("Poleberry");
			add("Grange A");
			add("Cloghdonnell");
			add("Ballinakill");
			add("Ballymackney");
			add("Fair Hill C");
			add("Decies");
			add("An Ghrafaidh");
			add("Kilworth");
			add("BÃƒÂ©al an Mhuirthead");
			add("Morrisson's Road");
			add("Glendree");
			add("Tallaght-Kingswood");
			add("Abbeymahon");
			add("Jamestown");
			add("Ballymun B");
			add("Callow");
			add("Malahide East");
			add("Kyle");
			add("Knockskagh");
			add("Kilbeacanty");
			add("Bencorr");
			add("Turnapin");
			add("Rockbarton");
			add("Dromore");
			add("Jamestown");
			add("Darver");
			add("Templeboy North");
			add("Commons");
			add("Rostellan");
			add("Woodford");
			add("Cormeen");
			add("Carker");
			add("Drummin");
			add("Imphrick");
			add("Oughtmama");
			add("Newbrook");
			add("Manulla");
			add("Corries");
			add("Turners Cross D");
			add("Cill AithnÃƒÂ­n");
			add("Wexford Rural");
			add("Rathrush");
			add("Tallanstown");
			add("Eskey");
			add("Killursa");
			add("Strokestown");
			add("Cloonusker");
			add("Tullamain");
			add("Bray No. 3");
			add("Wood Quay A");
			add("Loughan");
			add("Aughinish");
			add("Carrickart");
			add("Glendarragh");
			add("Tinahely");
			add("Sallyford");
			add("Clonbulloge");
			add("Kilteskill");
			add("Mocollop");
			add("Larah South");
			add("Castlekeeran");
			add("Lissadill East");
			add("Derry");
			add("Boherglass");
			add("Rossinan");
			add("Crossmolina North");
			add("Birr Rural");
			add("Killenaule");
			add("Gorteen");
			add("Dowra");
			add("Rodus");
			add("Knockaunbrandaun");
			add("Ballyboggan");
			add("Tipperary East Urban");
			add("Slievekeale");
			add("Mohill");
			add("Caher");
			add("Lisnaveane");
			add("Newtown");
			add("Clontibret");
			add("Clonfert");
			add("Greenville");
			add("Clash");
			add("Fethard");
			add("Kilbryan");
			add("Drumard");
			add("Longford No. 2 Urban");
			add("Claremorris");
			add("Kilfian South");
			add("Farahy");
			add("Mountrath");
			add("Kilglass");
			add("Lisdoonvarna");
			add("St. Peter's");
			add("Derrin");
			add("Carrickbeg Urban");
			add("Cabinteely-Pottery");
			add("Belhavel");
			add("Killone");
			add("Rathkenny");
			add("Lismaha");
			add("Teadies");
			add("Holycross");
			add("Dunmoylan West");
			add("Drumellihy");
			add("Donore");
			add("Cloone");
			add("Toghroinn FhÃƒÂ­onÃƒÂ¡in");
			add("Fermoy Urban");
			add("Killybegs");
			add("Donohill");
			add("Sliguff");
			add("Bandon");
			add("Tiscoffin");
			add("Raford");
			add("Killorglin");
			add("Curraglass");
			add("Raheny-St. Assam");
			add("Blackrock-Carysfort");
			add("Belleville");
			add("Drumline");
			add("Merchants Quay B");
			add("Monkstown Urban");
			add("Glentworth B");
			add("Barnameenagh");
			add("Kimmage A");
			add("Bodenstown");
			add("Douglas");
			add("Neale");
			add("Rathdangan");
			add("Pallas");
			add("Caherbarnagh");
			add("Hollymount");
			add("Donabate");
			add("Kenmare");
			add("Cahermore");
			add("Dysartmoon");
			add("Marblehill/Loughatorick");
			add("Inishannon");
			add("Ashtown B");
			add("Lumcloon");
			add("Mullyash");
			add("Kilbrittain");
			add("Garmna");
			add("Emlagh");
			add("Kiltallagh");
			add("Baltinglass");
			add("Rathmines West F");
			add("Clonroche");
			add("Carlow Urban");
			add("Creagh");
			add("Ballyin");
			add("Sundays Well B");
			add("Carrickbyrne");
			add("Cullahill");
			add("Rathfarnham-Butterfield");
			add("CeathrÃƒÂº an BhrÃƒÂºnaigh");
			add("Ballygarrett");
			add("Kellysgrove");
			add("Bear");
			add("Lorrha East");
			add("Kilbride");
			add("Boulteen");
			add("Gelshagh");
			add("Kilscannell");
			add("Kilmokea");
			add("Kilpatrick");
			add("Dunhill");
			add("Clooney");
			add("Borris-in-Ossory");
			add("Ballina");
			add("Shankill-Shanganagh");
			add("Duleek");
			add("Coolavin");
			add("Killoughrum");
			add("Ballynagar");
			add("Stradbally");
			add("Bunlahy");
			add("Longfordpass");
			add("Pilltown");
			add("Shannon B");
			add("Bolaboy");
			add("Gleneely");
			add("Baile Mhac Airt");
			add("Astee");
			add("Aghmacart");
			add("Whitehall A");
			add("Portnascully");
			add("Urney West");
			add("Castletown");
			add("Castledaly");
			add("Kilmacrenan");
			add("Oughterleague");
			add("Ballitore");
			add("John's B");
			add("Borris");
			add("Kimmage D");
			add("Lakeview");
			add("Boherboy");
			add("Elia");
			add("Kilmurry");
			add("Pollardstown");
			add("Prospect A");
			add("Ardmulchan");
			add("Castlecary");
			add("Hollywood");
			add("Reen");
			add("Drumcliff West");
			add("Clontarf East C");
			add("Knocktopher");
			add("Ballinacurra A");
			add("Smithstown");
			add("Fahan");
			add("Finglas South D");
			add("Nohaval");
			add("Monaghan Rural");
			add("Bishopstown B");
			add("Tallaght-Kilnamanagh");
			add("Gleann LÃƒÂ©ithÃƒÂ­n");
			add("Killaconenagh");
			add("Morrisson's Avenue East");
			add("Shronowen");
			add("Inishcaltra North/Inishcaltra South");
			add("South Dock");
			add("Garrymore");
			add("Loughanboy");
			add("Leighlinbridge");
			add("Rathfarnham Village");
			add("Kilballyowen");
			add("Deerpark");
			add("Rathcool");
			add("Oatfield");
			add("Watergrasshill");
			add("Swords Village");
			add("Rahoon");
			add("Street");
			add("Kildalky");
			add("Tulsk");
			add("City Hall A");
			add("Kilphelan");
			add("Manorhamilton");
			add("Boolteens");
			add("Coos");
			add("Garryvoe");
			add("Coolboy");
			add("Levally");
			add("Rathornan");
			add("Mountievers");
			add("ÃƒÂ�rainn");
			add("Killiskey");
			add("Killashee");
			add("Newtowngore");
			add("Delvin");
			add("Knocknagore");
			add("Inishlounaght");
			add("Bray No. 1");
			add("Cloonee");
			add("Port");
			add("Multyfarnham");
			add("Cloonoghill");
			add("Muinebeag (Bagenalstown) Urban");
			add("Rath");
			add("Clonin");
			add("Grangegeeth");
			add("Kilmeen");
			add("Dysart");
			add("Lismore Rural");
			add("Rathsallagh");
			add("Roscomroe");
			add("Collooney");
			add("Dripsey");
			add("O'Briensbridge");
			add("Doonane");
			add("Donaghpatrick");
			add("Killala");
			add("Rathmullan");
			add("Greystown");
			add("Durrow");
			add("St. Johnstown");
			add("Lattin");
			add("Thomastown");
			add("Stamullin");
			add("Ballynacarriga");
			add("Roanmore");
			add("Grange B");
			add("Ballyroan");
			add("Killeevan");
			add("Clonervy");
			add("Rathrobin");
			add("Inis Caoil");
			add("Kilmacteige");
			add("Garranes");
			add("Clane");
			add("Croaghmoyle");
			add("Ballydurn");
			add("Barna");
			add("Tallaght-Millbrook");
			add("Ardfield");
			add("Shrule");
			add("Cloonmore");
			add("Tullaghan");
			add("Kilflyn");
			add("Ballinamara");
			add("Woodfort");
			add("Kilglass South");
			add("Tombrack");
			add("Ballinteer-Broadford");
			add("Keereen");
			add("Eglish");
			add("Loughglinn");
			add("Glenkeen");
			add("Cabinteely-Kilbogget");
			add("Annagh");
			add("Doory");
			add("Coolattin");
			add("Moynsha");
			add("Cuttragh");
			add("Kilfinny");
			add("Ballinalack/Lackan");
			add("Kilmaclenine");
			add("Aughrim West");
			add("Dungarvan No. 1 Urban");
			add("Liscasey");
			add("Kilrainy");
			add("Raheen");
			add("Bangor");
			add("Rathluirc");
			add("Kinturk");
			add("Ballina Rural");
			add("Clonakilty Urban");
			add("Clogher");
			add("Tumna South");
			add("Ridge");
			add("Kilmihil");
			add("St. Canice");
			add("Ahascragh");
			add("Kilcummin");
			add("Kealkill");
			add("Templetouhy");
			add("Roskeen");
			add("Ballybrack");
			add("Kilcroan");
			add("Aughrim");
			add("Belturbet Urban");
			add("Wood Quay B");
			add("Bishopstown E");
			add("Ballymacarbry");
			add("Galvone B");
			add("Kiltannon");
			add("Killokennedy");
			add("Ballysax East");
			add("Kilmoylan");
			add("Ennis Rural");
			add("Eyrecourt");
			add("Kildinan");
			add("Denn");
			add("Ballymurphy");
			add("Lurraga");
			add("Ceanannas MÃƒÂ³r (Kells) Rural");
			add("Aughrim");
			add("Muckalee");
			add("Loughrea Rural");
			add("Brinny");
			add("Knockbarron");
			add("Ruan");
			add("Bishopstown A");
			add("Castle Ellis");
			add("Kilthomas");
			add("Ballyduff");
			add("Stonehall");
			add("Ballycroy North");
			add("Spancelhill");
			add("Ballysaggartmore");
			add("Moyacomb");
			add("Clontuskert");
			add("Clonkeen");
			add("Rathcoole");
			add("Kilcolagh");
			add("Scainimh");
			add("Marshalstown");
			add("Pembrokestown");
			add("Gleninagh");
			add("Lackan South");
			add("Hill of Down");
			add("Kilcaskan");
			add("Nealstown");
			add("Rathmacurkey");
			add("Kilcommon");
			add("Mountelva");
			add("Uskane");
			add("Castletown");
			add("Churchtown-Castle");
			add("Drummaan");
			add("Killyon");
			add("Aghnameadle");
			add("Kilglass");
			add("Nenagh Rural");
			add("Ogulla");
			add("Cloontra");
			add("Hopestown");
			add("Corraneary");
			add("MÃƒÂ¡rthain");
			add("Trumra");
			add("Bourney West");
			add("Rathaspick");
			add("Baile an Chalaidh");
			add("Cloghan");
			add("Urlee");
			add("Longford No. 1 Urban");
			add("Rotunda A");
			add("Blackrock-Central");
			add("Coolnaha");
			add("Termonfeckin");
			add("Borrisokane");
			add("Gleneely");
			add("Athy Rural");
			add("Glentworth C");
			add("Carrick-on-Shannon");
			add("Boherboy");
			add("Virginia");
			add("Kimmage B");
			add("Coolcraheen");
			add("Carnalway");
			add("Na Gleannta");
			add("Oakport");
			add("Ballycahill");
			add("Oldconnell");
			add("Cummer");
			add("Killeely B");
			add("Nobber");
			add("MÃƒÂ¡lainn Bhig");
			add("Dubber");
			add("Jerpoint West");
			add("Kilgarvan");
			add("Kilgobnet");
			add("Castleteheen");
			add("Clontarf East A");
			add("Kilkeasy");
			add("Mayo");
			add("Cahercorney");
			add("Cloghaun");
			add("Caddagh");
			add("Glanbehy");
			add("Knockglass");
			add("Danesfort");
			add("Blessington");
			add("Dromard East");
			add("Ballinascorney");
			add("Seefin");
			add("Ballaghaderreen");
			add("Bansha");
			add("Leitrim");
			add("The Glen A");
			add("Castleblayney Rural");
			add("Clongeen");
			add("Tawnawully");
			add("Rathfarnham-Hermitage");
			add("Baile ChlÃƒÂ¡ir");
			add("Kilcorney");
			add("Kilconnell");
			add("Coulagh");
			add("Priorswood E");
			add("Ballybrit");
			add("Tulla");
			add("Kilteevan");
			add("Cappavilla");
			add("Inishkeen");
			add("Kildorrery");
			add("Pembroke West C");
			add("Cloghera");
			add("Tincoora");
			add("Knockdrin");
			add("Letterbrickaun");
			add("Ballynamult");
			add("Kilshanny");
			add("Butler's Bridge");
			add("Oldleighlin");
			add("Kiltenanlea");
			add("Firhouse-Ballycullen");
			add("Julianstown");
			add("Skahanagh");
			add("Kiltubbrid");
			add("Kilrush");
			add("Kilmeadan");
			add("Columbkille");
			add("Lackalea");
			add("Tinnycross");
			add("Singland A");
			add("Coolmeen");
			add("Killenagh");
			add("Corkbeg");
			add("Clogher");
			add("Milltown");
			add("Anglesborough");
			add("Cloonlogher");
			add("Mullingar North Urban");
			add("Coolrus");
			add("Glassan");
			add("Ballycahalan");
			add("Ballybrackan");
			add("Tiknock");
			add("Brisha/Capard");
			add("Aclare");
			add("Kilnaneave");
			add("Harristown");
			add("Monivea");
			add("Drinagh");
			add("Derryloughan");
			add("Rathernan");
			add("Ratass");
			add("Bective");
			add("Greencastle");
			add("Custom House B");
			add("Lislea");
			add("Ballynaclogh");
			add("Glen");
			add("Pleberstown");
			add("Ballinacurra B");
			add("Park");
			add("Glennagannon");
			add("Grace Park");
			add("Kilcoke");
			add("Rackwallace");
			add("Cloghbrack");
			add("Shankill");
			add("Broadford");
			add("Glenties");
			add("Kilnamanagh");
			add("Johnstown");
			add("Tarbert");
			add("Knock North");
			add("Tallaght-Kiltipper");
			add("Douce");
			add("Graigue");
			add("Dumha Ãƒâ€°ige");
			add("Rathkeale Urban");
			add("Killadriffe");
			add("Killeenleagh");
			add("Shanbogh");
			add("Hilltown");
			add("Carrowkeel");
			add("The Ward");
			add("Ardmore");
			add("Killaconnigan");
			add("Sligo East");
			add("Kilkeary");
			add("Mogeely");
			add("Lackaghbeg");
			add("Rearymore");
			add("Athlone West Rural");
			add("Kilmeany");
			add("Brosna");
			add("Griffinstown");
			add("Bonnyglen");
			add("Coomlogane");
			add("Bumlin");
			add("Modelligo");
			add("Yugan");
			add("Kilbride");
			add("Killavally");
			add("Rathkeale Rural");
			add("Mahon A");
			add("Ballintober");
			add("Killower");
			add("Enniskeen");
			add("Ballingarry");
			add("Moveen");
			add("Ballinteer-Meadowmount");
			add("Glennamaddy");
			add("Bray No. 2");
			add("Ballymachugh");
			add("Cloontubbrid");
			add("Ennistimon");
			add("Windmill Cross");
			add("Attymass East");
			add("Shillelagh");
			add("Ballon");
			add("Tramore A");
			add("Kilreekill");
			add("Tullow Rural");
			add("Kilkishen");
			add("Kilmore");
			add("Moneenroe");
			add("Bunaveela");
			add("Ayle");
			add("Knockraha");
			add("Kilmacshane");
			add("Ballingate");
			add("Ballyphehane A");
			add("Geashill");
			add("Rathlynin");
			add("Rathoma");
			add("Killinure");
			add("Cootehill Rural");
			add("Screggan");
			add("Ardue");
			add("Kildangan");
			add("Keadew");
			add("Roundstone");
			add("Lurganboy");
			add("Arklow Rural");
			add("Kilfian East");
			add("Oldcastle");
			add("Ballybeagh");
			add("Rahalisk");
			add("Scregg");
			add("Gortkelly");
			add("Rossminoge");
			add("Cabinteely-Loughlinstown");
			add("Forgney");
			add("Newtownsandes");
			add("Drumcarn");
			add("Aglish");
			add("Ballyfarnan");
			add("Dungarvan No. 2 Urban");
			add("Querrin");
			add("Collinstown");
			add("Lullymore");
			add("An DÃƒÂºchoraidh");
			add("Doonasleen");
			add("Marymount");
			add("Ballysakeery");
			add("Shaen");
			add("Cill Ghabhlaigh");
			add("Letterkenny Rural");
			add("Killahy");
			add("Kilturra");
			add("Sallymount");
			add("Kilmurry");
			add("Shankill");
			add("Killeentierna");
			add("Cashel Urban");
			add("Newtown");
			add("Blackrock-Booterstown");
			add("Anketell Grove");
			add("Barna");
			add("Hinds");
			add("Streamstown");
			add("Craggs");
			add("Blackpool A");
			add("Athy West Urban");
			add("Glentworth A");
			add("Foxhall");
			add("Greenore");
			add("Croaghpatrick");
			add("Knockalla");
			add("Ballysax West");
			add("Coonard");
			add("DÃƒÂºn Chaoin");
			add("Ballyclerahan");
			add("Killathy");
			add("Naas Rural");
			add("Dalgan");
			add("Derreen");
			add("Ballycumber");
			add("Maas");
			add("Brownsford");
			add("Loughrea Urban");
			add("Adare North");
			add("Ashtown A");
			add("Galmoy");
			add("Treantaghmucklagh");
			add("Kilbride");
			add("Abbey A");
			add("Baile na Finne");
			add("Dock D");
			add("Ballinguile");
			add("Rathmines West E");
			add("Ahil");
			add("Ballycroy South");
			add("Ballyhane");
			add("Tomfinlough");
			add("Carrig");
			add("Killinaboy");
			add("Rathfarnham-Ballyroan");
			add("Corravaddy");
			add("An Carn MÃƒÂ³r");
			add("Aglish");
			add("Dunmain");
			add("Rathmoylan");
			add("Priorswood C");
			add("Innfield");
			add("Bennettsbridge");
			add("Sheepshead");
			add("ÃƒÂ�rainn MhÃƒÂ³r");
			add("Bahaghs");
			add("Pembroke West A");
			add("Murragh");
			add("Castlecor");
			add("Churchtown");
			add("Clonea");
			add("Cratloe");
			add("Myshall");
			add("Clondalkin Village");
			add("Kilfenora");
			add("Kilquain");
			add("Ballydehob");
			add("Kilmallock");
			add("Crossdoney");
			add("Ballymuigh");
			add("Kilconierin");
			add("Wexford No. 3 Urban");
			add("Whitechurch");
			add("St. Mary's");
			add("Castletown");
			add("Abbeyleix");
			add("Killeroran");
			add("Clarina");
			add("Milltown");
			add("Killeigh");
			add("Ballaghmoon");
			add("Rahill");
			add("Burry");
			add("Knockaree");
			add("Clohaskin");
			add("Glynn");
			add("Ballyfin");
			add("Ballynestragh");
			add("Oughterard");
			add("Market");
			add("Stonefield");
			add("Carthage");
			add("Cleaboy");
			add("Ballymahon");
			add("Carrig");
			add("Kilbride");
			add("Kiltorcan");
			add("Ballymacshaneboy");
			add("Finglas South C");
			add("Cloghard");
			add("Kilcockan");
			add("Dundalk Urban No. 3");
			add("Estersnow");
			add("Castlejordan");
			add("Dromard West");
			add("Anner");
			add("Kilcatherine");
			add("Dunmanoge");
			add("Lislaughtin");
			add("St. Kevin's");
			add("Cuilmore");
			add("Tullylease");
			add("Rathdowney");
			add("Knock South");
			add("Kilcornan");
			add("Creenasmear");
			add("Clonea");
			add("Knocknagree");
			add("Whitechurch");
			add("Bundoran Urban");
			add("Swords-Seatown");
			add("Barna");
			add("Caher");
			add("Lusmagh");
			add("Aughris");
			add("Carrigatogher");
			add("Kilmurry");
			add("Crumlin D");
			add("Kilgullane");
			add("Portlaoighise (Maryborough) Rural");
			add("Aghafin");
			add("Ballynahinch");
			add("CrÃƒÂ³ Chaorach");
			add("Ballyglass");
			add("Dungourney");
			add("Cloontuskert");
			add("Dunmoylan East");
			add("Terenure D");
			add("Milford");
			add("Rathcline");
			add("Ballinafad");
			add("Rathanna");
			add("Lackareagh");
			add("Galway Rural");
			add("Taghart");
			add("Blanchardstown-Roselawn");
			add("Magourney");
			add("Copperalley");
			add("Killavackan");
			add("Knocknaboley");
			add("Foxrock-Deans Grange");
			add("Ballinasloe Rural");
			add("Arklow No. 2 Urban");
			add("Calry");
			add("Creegh");
			add("Ballylanders");
			add("Lickeen");
			add("Mullingar South Urban");
			add("Annagh");
			add("Rathangan");
			add("Drumshanbo");
			add("Muinebeag (Bagenalstown) Rural");
			add("Dunlavin");
			add("Togher A");
			add("Drumroe");
			add("Newcastle");
			add("Templepeter");
			add("Killaloe");
			add("Mountheaton");
			add("Clogharinka");
			add("Ardnaree South Rural");
			add("Kilkee");
			add("Caherlag");
			add("Farranshoneen");
			add("Wicklow Rural");
			add("Ballinlough B");
			add("Kilgorman");
			add("Kilmeadan");
			add("Killimor");
			add("Newcastle Upper");
			add("Templetogher");
			add("Ballyhoge");
			add("Lissanover");
			add("Kilberry");
			add("Killerrig");
			add("Kilcolman");
			add("Abhainn Ghabhla");
			add("Garvagh/Arigna");
			add("Powerscourt");
			add("Riddlestown");
			add("Birr Urban");
			add("The Rower");
			add("Shreelane");
			add("Courtown");
			add("Ballingarry");
			add("Riversdale");
			add("Timoleague");
			add("Cabinteely-Granitefield");
			add("Tuckmill");
			add("Cashel West");
			add("Kilshenane");
			add("Ballindaggan");
			add("Kilmactranny");
			add("Rathsaran");
			add("Aughrim East");
			add("Clonbeg");
			add("Knockrea B");
			add("Mountbriscoe");
			add("Kilpatrick");
			add("Castlefinn");
			add("Hollywood");
			add("Kilnaseer");
			add("Doire FhÃƒÂ­nÃƒÂ­n");
			add("Beihy");
			add("Desertegny");
			add("Kilcolumb");
			add("Baslick");
			add("Patrickswell");
			add("Killilagh");
			add("Rathealy");
			add("Flesk");
			add("Rahelty");
			add("Ballinteer-Woodpark");
			add("Milltown");
			add("Island");
			add("Navan Rural");
			add("Bellananagh");
			add("Galbally");
			add("Bishopstown D");
			add("Kilmore B");
			add("Galvone A");
			add("Carrownagur");
			add("Clondarrig");
			add("Clare Island");
			add("Doonbeg");
			add("Carrickaslane");
			add("Ballymore Eustace");
			add("Attymass West");
			add("Rahan");
			add("Gaile");
			add("Coole");
			add("Terenure-Cherryfield");
			add("Bishopstown");
			add("Wellpark");
			add("Kilcolmanbane");
			add("Tullow Urban");
			add("Dunkineely");
			add("Killanena");
			add("Mothell");
			add("Killererin");
			add("Ballyhar");
			add("Arran Quay D");
			add("DÃƒÂºn Laoghaire-Mount Town");
			add("Dysart");
			add("Castlehaven South");
			add("Laragh");
			add("Corrofin");
			add("Teltown");
			add("Ballyphehane B");
			add("Kilderry");
			add("Dock B");
			add("Carrigallen East");
			add("Rathmichael (Bray)");
			add("Rathmines West C");
			add("Clonfert East");
			add("Cloncurry");
			add("Acaill");
			add("Sonna");
			add("Templebodan");
			add("Kilpipe");
			add("Shronell");
			add("Glenco/Sheskin");
			add("Derreen");
			add("Palmerston West");
			add("Sillerna");
			add("Glanlee");
			add("Ballymore");
			add("Gneeves");
			add("Drumcreehy");
			add("Castlerahan");
			add("Ballygall C");
			add("Derrinboy");
			add("Cloonown");
			add("Knockroe");
			add("Houndswood");
			add("Clonpriest");
			add("Carnew");
			add("Pembroke East D");
			add("Ford");
			add("Ballyporeen");
			add("St. Martin's");
			add("Ennis No. 4 Urban");
			add("Kilcommock");
			add("Clondalkin-Moorfield");
			add("Mervue");
			add("Heathstown");
			add("Carrafin");
			add("Tinnahinch");
			add("Ardamullivan");
			add("Moynalty");
			add("Glengarriff");
			add("Moyanna");
			add("Sraheen");
			add("Ardbraccan");
			add("Rossmore");
			add("Noughaval");
			add("Mount Bellew");
			add("Twomileborris");
			add("Kilpatrick");
			add("Huntston");
			add("Ballylusky");
			add("Kilclonfert");
			add("Naas Urban");
			add("Haroldstown");
			add("Balrathboyne");
			add("Munterconnaught");
			add("Dromard");
			add("Clonarney");
			add("Castlesaunderson");
			add("DÃƒÂºn Urlann");
			add("Ballybrittas");
			add("Newport");
			add("Tinamuck");
			add("Newtown");
			add("Doon");
			add("Banagher");
			add("An Machaire");
			add("Centre A");
			add("Kilfelim");
			add("Lacka");
			add("Foilnaman");
			add("Sixmilebridge");
			add("Kilfane");
			add("Kilfergus");
			add("Bragan");
			add("Castlerichard");
			add("Dalkey-Bullock");
			add("Crossna");
			add("Rahinstown");
			add("Castleconor West");
			add("Ardsallagh");
			add("Scart");
			add("Castledermot");
			add("Kiltomy");
			add("Roscommon Urban");
			add("Usk");
			add("Gortnascreeny");
			add("Garrymore");
			add("Tullyvin East");
			add("Ballymaclode");
			add("Caherduggan");
			add("Kilmanagh");
			add("Ballylynan");
			add("Priorswood D");
			add("Eanymore");
			add("Killogilleen");
			add("Coolhill");
			add("Rathmore");
			add("Killukin");
			add("Ballintra");
			add("Crumlin B");
			add("Baile an Sceilg");
			add("Urlingford");
			add("Thomastown");
			add("Painestown");
			add("Pembroke West B");
			add("Rathclarin");
			add("Bundoran Rural");
			add("Rowls");
			add("An Turlach");
			add("Knockainy");
			add("Terenure B");
			add("Inishkenny");
			add("Dalystown");
			add("Rockingham");
			add("Nurney");
			add("Edmondstown");
			add("Einagh");
			add("Shanballymore");
			add("Keshcarrigan");
			add("Blanchardstown-Delwood");
			add("Kiltullagh");
			add("Carrig");
			add("Portarlington North");
			add("Loughill/Cloonacool");
			add("Aultagh");
			add("Cloyne");
			add("Killallon");
			add("Killaraght");
			add("Glenhest");
			add("Moviddy");
			add("Killian");
			add("Glengort");
			add("Killarney Urban");
			add("Mullingar Rural");
			add("Corrala");
			add("Carn");
			add("Ballybeg North");
			add("Culliagh");
			add("Rathvilly");
			add("Tivoli A");
			add("Finnoe");
			add("Harperstown");
			add("Carrick");
			add("Urlaur");
			add("Gortermone");
			add("Cahore");
			add("Edmondstown");
			add("Ashfield");
			add("Carrigaline");
			add("Custom House A");
			add("Rosslare");
			add("Cashel");
			add("Cashel East");
			add("Castleconnell");
			add("Fanad West");
			add("Kilcumreragh");
			add("Newtown");
			add("Moneystown");
			add("Tullycorbet");
			add("Grantstown");
			add("Sundays Well A");
			add("Castlerickard");
			add("Moyrus");
			add("Boola");
			add("Inchaquire");
			add("Galtrim");
			add("Ballynakill");
			add("Bantry Urban");
			add("Templetown");
			add("Durrus West");
			add("Kilbarron");
			add("Fenoagh");
			add("Attanagh");
			add("Headfort");
			add("Fore West");
			add("Letterkenny Urban");
			add("Drumwood");
			add("Kilcooly");
			add("Kilcomenty");
			add("Crumlin E");
			add("Portlaoighise (Maryborough) Urban");
			add("Westport Rural");
			add("Ballyegan");
			add("Greenpark");
			add("Binbane");
			add("Ballyconnell");
			add("Shankill-Rathsallagh");
			add("Cloonygormican");
			add("Kilwatermoy West");
			add("Ushers A");
			add("Nad");
			add("Kilgolagh");
			add("Dromin");
			add("Ballyhean");
			add("Mountcollins");
			add("Birdstown");
			add("Muckalee");
			add("Shannon A");
			add("Termon");
			add("Blanchardstown-Tyrrelstown");
			add("Mashanaglass");
			add("Drumanespick");
			add("Aglishcloghane");
			add("Foxrock-Torquay");
			add("Killykeen");
			add("Ballymacward");
			add("Pollrone");
			add("Ballingarry");
			add("Carney");
			add("Castlecrine");
			add("Inns Quay C");
			add("Warrenscourt");
			add("Ardee Urban");
			add("Dawsongrove");
			add("Kilmurry");
			add("Ballymacool");
			add("Thomastown");
			add("Drumsna");
			add("Drinagh");
			add("Glenstal");
			add("Togher B");
			add("Templeogue-Osprey");
			add("Ballymackean");
			add("Carlingford");
			add("Slievemore");
			add("Tullowbeg");
			add("Killeely");
			add("Kilmacar");
			add("BÃƒÂ©al Deirg MÃƒÂ³r");
			add("Lowertown");
			add("Carrigaline");
			add("DÃƒÂºn Laoghaire-Glenageary");
			add("Killure");
			add("Cape Clear");
			add("Aghowle");
			add("Dundalk Rural");
			add("Riverstown");
			add("Ballinlough C");
			add("Castleblakeney");
			add("Cordal");
			add("Balraheen");
			add("Kilmalinoge");
			add("Marshalstown");
			add("Forth");
			add("Munakill");
			add("Rinvyle");
			add("Glenade");
			add("Uregare");
			add("Altidore");
			add("Ballygall A");
			add("Tullamore Urban");
			add("Leitrim");
			add("Rathfeston");
			add("Ballyphilip");
			add("Ballinglen");
			add("Pembroke East B");
			add("Monaseed");
			add("Kilsheelan/Killaloan");
			add("Coolballintaggart");
			add("Carn");
			add("Ennis No. 2 Urban");
			add("Ardough");
			add("Clondalkin-Dunawley");
			add("Lough Atalia");
			add("O'Dempsey");
			add("Cliff");
			add("The Grange");
			add("Kinawley");
			add("Tara");
			add("Dunaff");
			add("Kilbonane");
			add("Kilculliheen");
			add("Roxborough");
			add("Limerick");
			add("Moynehall");
			add("Lisduggan");
			add("Gallen");
			add("Rooskagh");
			add("Kilmore C");
			add("Ballinamore");
			add("Kilchreest");
			add("An CorrÃƒÂ¡n");
			add("Silverbrook");
			add("Carrickatee");
			add("Bilberry");
			add("Loughcurrane");
			add("Coolrain");
			add("Graigue");
			add("Terenure-Greentrees");
			add("Blackpool");
			add("Ballinasloe Urban");
			add("Leitir Mhic an Bhaird");
			add("Abbeyville");
			add("Kilmullen");
			add("Arran Quay E");
			add("DÃƒÂºn Laoghaire-Sallynoggin East");
			add("Glenroe/Ballyeighter");
			add("Kilvemnon");
			add("Stranorlar");
			add("An ClochÃƒÂ¡n Liath");
			add("Clonskeagh-Windy Arbour");
			add("Dock C");
			add("Belclare");
			add("Wicklow Urban");
			add("Esker/Ballaghassaan");
			add("Rathmines West D");
			add("Kilconny");
			add("Donadea");
			add("Templemartin");
			add("Templenacarriga");
			add("Stillorgan-Priory");
			add("Cloonkeen");
			add("Kilmeage South");
			add("Goolamore");
			add("Mallow Rural");
			add("Noughaval/Castletown");
			add("Church Hill");
			add("New Birmingham");
			add("Aghinagh");
			add("Kerryhead");
			add("Killamery");
			add("Kilglass North");
			add("Ballygall D");
			add("Ballyvool");
			add("Crannagh");
			add("Ballynahaglish");
			add("Anagaire");
			add("Cherry Orchard C");
			add("Tralee Urban");
			add("Longford Rural");
			add("Corracharra");
			add("Crosskeys");
			add("Pembroke East E");
			add("Ballynoe");
			add("Crohane");
			add("Croom");
			add("Cabra West D");
			add("Bealock");
			add("Durrow");
			add("Carrowreagh");
			add("Clondalkin-Rowlagh");
			add("Redcastle");
			add("Murroogh");
			add("Kilnamartery");
			add("Blanchardstown-Coolmine");
			add("Newcastle");
			add("Ardrahan");
			add("Curraghmore");
			add("Aillemore");
			add("Raheny-Foxfield");
			add("Seskinan");
			add("Rodanstown");
			add("Killylough");
			add("Grange");
			add("Mounthazel");
			add("Upperchurch");
			add("Piercetown");
			add("Macloneigh");
			add("Knockgraffon");
			add("Kilmainham B");
			add("Kilcumreragh");
			add("Kilkelly");
			add("Kineagh");
			add("Solloghodbeg");
			add("Glasheen C");
			add("Kilcormick");
			add("Cloghprior");
			add("Cavan Rural");
			add("Ballycarroll");
			add("Castleknock-Park");
			add("Rossard");
			add("Lissadill North");
			add("Derrycunlagh/Derrylea");
			add("Rosscarbery");
			add("Centre B");
			add("Ballylarkin");
			add("Fedamore");
			add("Agharra");
			add("Redwood");
			add("Killinick");
			add("Gortnapeaky");
			add("Ballinacarrig");
			add("Killurin");
			add("South Gate A");
			add("Faughart");
			add("Lisronagh");
			add("Churchtown");
			add("Cloghan");
			add("Dromore");
			add("Dunganstown South");
			add("Ballinspittle");
			add("Curraclone");
			add("Carrickbeg Rural");
			add("Mallardstown");
			add("Abington");
			add("Athlone West Urban");
			add("Grousehall");
			add("Mortlestown");
			add("Moyclare");
			add("Crumlin C");
			add("Portarlington South");
			add("Turrock");
			add("Ballyconry");
			add("Coolure");
			add("Carrickboy");
			add("Derrylaur");
			add("Killiney South");
			add("Martry");
			add("Terenure C");
			add("Castlemagner");
			add("Newtown Forbes");
			add("Culnacleha");
			add("Glenagower");
			add("Boolyglass");
			add("Rathbane");
			add("Glenlough");
			add("Blanchardstown-Mulhuddart");
			add("Churchtown");
			add("Owenmore");
			add("Doon South");
			add("Foxrock-Carrickmines");
			add("Aughrim");
			add("Ballyconra");
			add("Kilgeever");
			add("Dock A");
			add("Cooraclare");
			add("Inns Quay A");
			add("Listowel Urban");
			add("Ballyhaunis");
			add("Glasheen B");
			add("Cadamstown");
			add("Kilbennan");
			add("Templemichael");
			add("Drumlosh");
			add("Caherconlish East");
			add("Tivoli B");
			add("Templeogue-Limekiln");
			add("Moore");
			add("Beaumont D");
			add("Tullycreen");
			add("Clogh");
			add("Ardnaree North");
			add("Ballybane");
			add("Fairymount");
			add("Blarney");
			add("DÃƒÂºn Laoghaire-East Central");
			add("Islandikane");
			add("Trooperstown");
			add("Dunshaughlin");
			add("Toberpatrick East");
			add("Tulla");
			add("Mountain");
			add("Glenbrohane");
			add("Tubrid");
			add("Quinsborough");
			add("Cloonkeen");
			add("CÃƒÂ© BhrÃƒÂ©anainn");
			add("Newcastle Lower");
			add("Aghalateeve/Aghanlish");
			add("Killedmond");
			add("Cahermurphy");
			add("Grennanstown");
			add("Cnoc na RÃƒÂ¡ithe");
			add("Ballintemple");
			add("Kilmacanoge");
			add("Ballybough A");
			add("Trim Rural");
			add("Annaduff");
			add("Rahan");
			add("Kilbonane");
			add("Centre B");
			add("Emly");
			add("Avoca");
			add("Merchants Quay F");
			add("Templeomalus");
			add("Togher");
			add("Clonoulty East");
			add("Ballymagauran");
			add("Calary");
			add("Drumlish");
			add("Clondalkin-Ballymount");
			add("Kinsalebeg");
			add("Killoughy");
			add("Altnapaste");
			add("Scregg");
			add("Hartstown");
			add("Rathfeigh");
			add("Buncrana Rural");
			add("Milltown Malbay");
			add("Lisdowney");
			add("Limerick South Rural");
			add("Rossmore");
			add("Ballintra");
			add("Kingsmeadow");
			add("Kentstown");
			add("Duntryleague");
			add("Kilmore A");
			add("Clonaslee");
			add("Bullaun");
			add("Taghmon");
			add("Broomfield");
			add("Kiltullagh");
			add("Inchigeelagh");
			add("Ballymascanlan");
			add("Cashel Rural");
			add("Killyon");
			add("Templeogue Village");
			add("Ballynaglogh");
			add("Castlering");
			add("Breandrum");
			add("Ballysimon");
			add("Castlecuffe");
			add("Cabra West A");
			add("Castledockrell");
			add("DÃƒÂºn Laoghaire-Monkstown Farm");
			add("Castlehaven North");
			add("Skreen");
			add("Cullane");
			add("Clonskeagh-Milltown");
			add("Crinny");
			add("Bunnybeg");
			add("Bridgetown");
			add("Edenderry Rural");
			add("Kilvine");
			add("Rathmines West B");
			add("Derrymore");
			add("Barleyhill");
			add("Celbridge");
			add("Mitchelstown");
			add("Cloonyquin");
			add("Tallow");
			add("Killashee");
			add("Gleann Chaisil");
			add("Kilshannig");
			add("Carran");
			add("Largymore");
			add("Palmerston Village");
			add("Dromore");
			add("Ballycummin");
			add("Ballygall B");
			add("Castlereagh");
			add("Outrath");
			add("Moher");
			add("Abbeydorney");
			add("Carrowbaun");
			add("Machaire Chlochair");
			add("Dungarvan Rural");
			add("Blackrock-Williamstown");
			add("Monaghan Urban");
			add("Ballybeg");
			add("Pembroke East C");
			add("Breencorragh");
			add("Firmount");
			add("Kiltinan");
			add("Crean");
			add("Rahona");
			add("Knocknaheeny");
			add("Killinthomas");
			add("Breedoge");
			add("Ennis No. 3 Urban");
			add("Moville");
			add("Clondalkin-Monastery");
			add("Menlough");
			add("Aghadown North");
			add("Canningstown");
			add("Beaumont E");
			add("Ballysteen");
			add("Cloonkeen");
			add("Crossakeel");
			add("Rathcoole");
			add("Artagh South");
			add("Bantry Rural/Whiddy");
			add("Mountstuart");
			add("Dunboyne");
			add("Walkinstown B");
			add("Fleanmore");
			add("Killincooly");
			add("Mullagh");
			add("Glenfarn");
			add("Thurles Rural");
			add("Military Road");
			add("Hammerlane");
			add("Mothel");
			add("Hacketstown");
			add("Killard");
			add("Castlelyons");
			add("Tullaghmelan");
			add("Bracklin");
			add("Bruce Hall");
			add("Dangans");
			add("Creggs");
			add("Ballyvaldon");
			add("Skreen");
			add("Clifden");
			add("Kilmoylerane");
			add("Bilberry");
			add("Doon");
			add("Kilmurry");
			add("Borrisoleigh");
			add("Kiltoraght");
			add("Ballynoe West");
			add("Skeagh");
			add("Dalkey-Avondale");
			add("Williamstown");
			add("Shandon A");
			add("Laracor");
			add("Kill");
			add("Kilmurry");
			add("Tibradden");
			add("Kildellig");
			add("Roscommon Rural");
			add("Ballyhuskard");
			add("Timahoe South");
			add("Ballyjamesduff");
			add("Drishane");
			add("Manch");
			add("Kilbeacon");
			add("Poyntstown");
			add("Kilmaganny");
			add("Ballyarthur");
			add("Ballyadams");
			add("Shanagolden");
			add("Ards");
			add("Ballynorig");
			add("Dromoyle");
			add("Crumlin A");
			add("Tubbridbrittain");
			add("Crossalare");
			add("Croghan");
			add("Knocknahoe");
			add("Killoscully");
			add("Clonleigh North");
			add("Glencullen");
			add("Emlygrennan");
			add("Slane");
			add("Terenure A");
			add("Tobercurry");
			add("Greenfort");
			add("Currygrane");
			add("Castlesampson");
			add("Dromcolliher");
			add("Cullen");
			add("Scotsborough");
			add("Rockhill");
			add("Ballyhealy");
			add("Blanchardstown-Corduff");
			add("Templedouglas");
			add("Dromin");
			add("Clogher");
			add("Lismakeery");
			add("Raheny-Greendale");
			add("Killadoon");
			add("Woolengrange");
			add("Erriff");
			add("Coolraine");
			add("Kilbrogan");
			add("Raferagh");
			add("Harmonstown A");
			add("Milltown");
			add("Athy East Urban");
			add("Ballinamore");
			add("Kilmainham C");
			add("Cobh Rural");
			add("Clonbern");
			add("Killedan");
			add("Templeneiry");
			add("Milltown");
			add("The Lough");
			add("Templeogue-Cypress");
			add("Morristownbiller");
			add("Drummin");
			add("Clonmethan");
			add("Greenane");
			add("Fenagh");
			add("Castleplunket");
			add("Arvagh");
			add("Ballymartle");
			add("Dundrum-Sweetmount");
			add("Drumcannon");
			add("Clomantagh");
			add("Rathaspick");
			add("Castleconor East");
			add("Garrane");
			add("Doire Ianna/Cloon");
			add("Clooney");
			add("Ballynadrumny");
			add("Headford");
			add("Kilmore");
			add("Tehallan");
			add("South Gate B");
			add("An Cnoc BuÃƒÂ­");
			add("Kellistown");
			add("Lisheen");
			add("Gallow");
			add("Moing na BÃƒÂ³");
			add("Knockrath");
			add("Durrus East");
			add("Killabban");
			add("Ardmore");
			add("Ballymore");
			add("Ballybricken");
			add("Browningstown");
			add("Athlone East Rural");
			add("Ballycarron");
			add("Seirkieran");
			add("Oughterard");
			add("Glensharrold");
			add("Newbawn");
			add("Ballyduff");
			add("Finnea");
			add("Drumkeary");
			add("Shankill-Rathmichael");
			add("Killeagh");
			add("Reisk");
			add("Greaghglass/Stralongford");
			add("Latteragh");
			add("Drumsnat");
			add("Kilrush Urban");
			add("Monagay");
			add("Killary");
			add("Ballyliffin");
			add("Wexford No. 2 Urban");
			add("Fiddown");
			add("St. Laurence");
			add("Kilbixy");
			add("Stradbally");
			add("Thurles Urban");
			add("Kilnagross");
			add("Culdaff");
			add("Grange Upper");
			add("Glendalough");
			add("Kilmakevoge");
			add("Adare South");
			add("Inns Quay B");
			add("Nodstown");
			add("Ardee Rural");
			add("Bocks");
			add("Bawn");
			add("Ennis No. 1 Urban");
			add("Whitecastle");
			add("Laurencetown");
			add("Cloonkeen");
			add("Danganbeg");
			add("Templeogue-Orwell");
			add("Pedara Vohers/Tircahan");
			add("Ballyfoyle");
			add("Barronstown");
			add("Slievemahanagh");
			add("Ballygibbon");
			add("Kilcronat");
			add("Kincraigy");
			add("DÃƒÂºn Laoghaire-Glasthule");
			add("Kilbarry");
			add("Caheragh");
			add("Drummullagh");
			add("Toberpatrick West");
			add("Derrycastle");
			add("Finglas South B");
			add("Caltra");
			add("Griston");
			add("Abbey B");
			add("Ballintogher East");
			add("Clonfad");
			add("Gleann Cholm Cille");
			add("Skerries");
			add("Castlegregory");
			add("Course");
			add("Bourney East");
			add("Royal Exchange B");
			add("Clonmeen");
			add("Aghavoghill/Melvin");
			add("Dooish");
			add("Glenmore");
			add("Ballycottin");
			add("Ballybough B");
			add("Carrowduff");
			add("Swords-Lissenhall");
			add("Burncourt");
			add("Glenaniff");
			add("Raheenakeeran");
			add("Churchfield");
			add("DÃƒÂºn LÃƒÂºiche");
			add("Blackrock-Stradbrook");
			add("Mahanagh");
			add("Ballinaclash");
			add("Sligo West");
			add("Pembroke East A");
			add("Ballymoney");
			add("Dangan");
			add("Clonoulty West");
			add("Gurranebraher D");
			add("Drehid");
			add("Kilshanvy");
			add("Cronebane");
			add("Tuam");
			add("Clondalkin-Cappaghmore");
			add("Knocknacarragh");
			add("Lack");
			add("Graigabbey");
			add("Arran Quay B");
			add("Mountshannon");
			add("Dunkerrin");
			add("Castlegannon");
			add("Dunmore North");
			add("Moy");
			add("Tipperary Rural");
			add("Ushers F");
			add("Carrigrohane Beg");
			add("Kilnahue");
			add("Larchville");
			add("Toberroe");
			add("Newmarket");
			add("Tullaghan");
			add("Bawnboy");
			add("Killermogh");
			add("Kinnitty");
			add("Killoran");
			add("Kilgarvan");
			add("Girley");
			add("Kyle South");
			add("Ardamine");
			add("Kilfian West");
			add("Glen");
			add("Abbeyfeale");
			add("Gorey Urban");
			add("Clonskeagh-Roebuck");
			add("Ballyburly");
			add("Grilly");
			add("Ballycarney");
			add("Ardagh");
			add("Cliffony South");
			add("Ballincrea");
			add("Cregga");
			add("Ballynakill");
			add("Rathowen");
			add("Kilmeage North");
			add("Liscarroll");
			add("Castlewray");
			add("Mullinahone");
			add("Fossy");
			add("Kilgefin");
			add("Newcastle Rural");
			add("Ballyhale");
			add("Kilgobban");
			add("Maperath");
			add("MÃƒÂ­n an Chladaigh");
			add("Carrickmacross Rural");
			add("Shannonbridge");
			add("Cartron");
			add("Carrig");
			add("Glenville");
			add("Burtown");
			add("Crecora");
			add("Edenderry Urban");
			add("Drung");
			add("Knockrea A");
			add("Carnagh");
			add("Newtown Cunningham");
			add("Kilcommon");
			add("Aghadown South");
			add("Ballyragget");
			add("Knocklong");
			add("Beaumont F");
			add("Mansfieldstown");
			add("Waterloo");
			add("Killaspuglonane");
			add("Athleague East");
			add("Clontarf West D");
			add("Ringville");
			add("Tullaherin");
			add("Glaslough");
			add("Castle C");
			add("Walkinstown C");
			add("Glin");
			add("Bishopstown C");
			add("Turmone");
			add("Grange D");
			add("An CrompÃƒÂ¡n");
			add("Kilmainham A");
			add("Ballincollig");
			add("Ballyfermoyle");
			add("Portlaw");
			add("Greenhall/Lackagh");
			add("Killimer");
			add("Castletownroche");
			add("Tallaght-Springfield");
			add("Sramore");
			add("Rush");
			add("Eanach DhÃƒÂºin");
			add("Glanlough");
			add("Templeboy South/Mullagheruse");
			add("Cushkillary");
			add("Rathbarry");
			add("Ballinteer-Marley");
			add("Shantalla");
			add("Jerpoint Church");
			add("Greagh");
			add("Dunnaman");
			add("Curraghbeg");
			add("Urlan");
			add("Maynooth");
			add("Carrowrevagh");
			add("Toomore");
			add("Agha");
			add("Shandon B");
			add("Grangeford");
			add("Castletown");
			add("Kinsale Urban");
			add("Gort");
			add("Williamstown");
			add("Barrowhouse");
			add("Colmanstown");
			add("Daingean");
			add("Derryvillane");
			add("Fermoy Rural");
			add("Fortland");
			add("Drumcullen");
			add("Letterfore");
			add("Moyaliff");
			add("Kilraghtis");
			add("Ballincloher");
			add("Ardmayle");
			add("Killiney North");
			add("Carlow Rural");
			add("Stackallan");
			add("Cavan Urban");
			add("Abhainn Bhrain");
			add("Cleanglass");
			add("Muckanagh");
			add("Dromtrasna");
			add("Curraheen");
			add("Clogher");
			add("Skeagh");
			add("Rosbercon Urban");
			add("Tullaghanbrogue");
			add("Prospect B");
			add("Ballynaskeagh");
			add("Ballyarr");
			add("Kilmacthomas");
			add("Rathronan");
			add("Auburn");
			add("Enagh");
			add("Dysert");
			add("Balleen");
			add("Custom House");
			add("Annayalla");
			add("Colman");
			add("Harmonstown B");
			add("Breanrisk");
			add("Ballindine");
			add("Carnagh");
			add("Mintiaghs");
			add("Money");
			add("Moone");
			add("Ballyvarra");
			add("Ballysadare East");
			add("Templeogue-Kimmage Manor");
			add("Dromina");
			add("Granard Urban");
			add("Emlagh");
			add("Lorrha West");
			add("Dunmore");
			add("Dundrum-Taney");
			add("Gortnavern");
			add("Faithlegg");
			add("Kilberrihert");
			add("Srah");
			add("Drumfin");
			add("Doon West");
			add("Finglas North C");
			add("Dundalk Urban No. 1");
			add("Tralee Rural");
			add("Dawros");
			add("Nurney");
			add("Hillsbrook");
			add("Valencia");
			add("Knigh");
			add("Tallaght-Killinardan");
			add("Dunmanway South");
			add("Drumcar");
			add("Kilbride");
			add("Rinealon");
			add("Na Monga");
			add("Carrigtohill");
			add("Ayrfield");
			add("Rossmore");
			add("Swords-Forrest");
			add("Killimor");
			add("Lisgoold");
			add("Doonis");
			add("Centre A");
			add("Blackrock-Newpark");
			add("Lisheenavalla");
			add("Imael South");
			add("Merchants Quay E");
			add("Lisagoan");
			add("Meens");
			add("An Ros");
			add("Maum");
			add("Tober");
			add("Gurranebraher B");
			add("Carrick");
			add("Gortnagullion");
			add("Delgany");
			add("Manorcunningham");
			add("Bohernabreena");
			add("Kilconickny");
			add("Kilcullen");
			add("Killygar");
			add("Eadestown");
			add("Tinnahinch");
			add("Ballymodan");
			add("Culmullin");
			add("Bramblestown");
			add("Toberadosh");
			add("Quin");
			add("BÃƒÂ©al ÃƒÂ�tha an Ghaorthaidh (Maigh Chromtha)");
			add("Whitechurch");
			add("Ushers D");
			add("Kinsale Rural");
			add("Knocks");
			add("Kilbarry");
			add("Ardcavan");
			add("Bracklagh");
			add("Killeagh");
			add("Streamstown");
			add("Lismanny");
			add("Collon");
			add("Taghboy");
			add("Kilcormac");
			add("Annagh");
			add("Whitechurch");
			add("Ballymackey");
			add("Killanny");
			add("Cardtown");
			add("Castleboro");
			add("Shanid");
			add("Doe Castle");
			add("Gracedieu");
			add("Borrisnoe");
			add("Monkstown Rural");
			add("Clonskeagh-Farranboley");
			add("Ardcath");
			add("Nenagh West Urban");
			add("Kilcolman");
			add("Clonlost");
			add("Glengesh");
			add("Glenwilliam");
			add("Moydow");
			add("Cloonfinlough");
			add("Cappoquin");
			add("Glore");
			add("Kill");
			add("Inch");
			add("Feddyglass");
			add("Modelligo");
			add("Mullanalaghta");
			add("Artagh North");
			add("Kildimo");
			add("Odagh");
			add("Lixnaw");
			add("Gort an Choirce");
			add("Blackrock-Templehill");
			add("Donaghmore");
			add("Branchfield/Carrownaskeagh");
			add("Templeglentan");
			add("Garrown");
			add("Belan");
			add("Lahard");
			add("Corboy");
			add("Gurranebraher E");
			add("Kilcar");
			add("Dunfierth");
			add("Buttevant");
			add("Drumlumman");
			add("Coolagarranroe");
			add("Templemolaga");
			add("Robertstown");
			add("Glashare");
			add("Arran Quay C");
			add("Edenacarnan");
			add("Ogonnelloe");
			add("Paulstown");
			add("Athlacca");
			add("Clontarf West B");
			add("Ballybeg South/Ballynaneashagh");
			add("Newtown");
			add("Stonyford");
			add("Anny");
			add("Ardagh");
			add("Walkinstown A");
			add("Abbey C");
			add("Straid");
			add("Moyarta");
			add("Ballynakill");
			add("Kilflyn");
			add("Inchicore A");
			add("Barnacurra");
			add("Wells");
			add("Newport West");
			add("Newport's Square");
			add("Kilcogy");
			add("Formoyle");
			add("Newtown");
			add("Ballycastle");
			add("Portmarnock North");
			add("Boyounagh");
			add("Canuig/MÃƒÂ¡istir Gaoithe");
			add("Gaybrook");
			add("Toomour");
			add("Cleggan");
			add("Kilmaloda West");
			add("Cabra East C");
			add("St. Nicholas");
			add("Derryad");
			add("Creeve");
			add("Toberbreeda");
			add("Roslee");
			add("Gort na Tiobratan");
			add("Kilgarvan");
			add("Rathmines West A");
			add("Castlefore");
			add("Balloughter");
			add("Bekan");
			add("Farranrory");
			add("Shanakiel");
			add("Inch");
			add("Kilballyowen");
			add("Dunkitt");
			add("Newcastle");
			add("Doorus");
			add("Huntingdon");
			add("Templeport/Benbrack");
			add("Kinneigh");
			add("Farnoge");
			add("Annaghdown");
			add("Tinnacross");
			add("Caherhurley");
			add("Skagh");
			add("Timahoe");
			add("Newcastle Urban");
			add("Ardnamullan");
			add("Templemore");
			add("Riverstown");
			add("Brockagh");
			add("Pouladuff A");
			add("Clonmore");
			add("Kilnanare");
			add("Cloghjordan");
			add("Carrigeen");
			add("Borris");
			add("Carrickleck");
			add("Graddum");
			add("Cappagh");
			add("Abbeygormacan");
			add("Ardcolm");
			add("Aghavas");
			add("Ballickmoyler");
			add("Clonmel Rural");
			add("Bailieborough");
			add("Enniscorthy Urban");
			add("Castlecomer");
			add("Particles");
			add("Ballinlough");
			add("Derrylahan");
			add("Rathgormuck");
			add("Kilmeedy");
			add("Graigue Rural");
			add("Littleton");
			add("Dunmakeever/Derrynananta");
			add("Rosmead");
			add("Ullard");
			add("Castle D");
			add("Grange E");
			add("Loughfea");
			add("Ticor North");
			add("Grangemellon");
			add("Aghamore");
			add("Killeen");
			add("Cooleagh");
			add("Derrygorry");
			add("Ballygarvan");
			add("Rathdrum");
			add("Lackagh");
			add("Ballintober");
			add("Tallaght-Tymon");
			add("Easky West");
			add("Ladytown");
			add("Leitrim");
			add("Hospital");
			add("Emyvale");
			add("Ballytruckle");
			add("Glanmore");
			add("Coolcraheen");
			add("Inis Mhic an Doirn");
			add("Ballinteer-Meadowbroads");
			add("Taylors Hill");
			add("Baunmore");
			add("Leighmoney");
			add("Millbrook");
			add("Buncrowey");
			add("Finglas North A");
			add("Darrynane");
			add("St. Laurence Gate");
			add("Burren");
			add("Caher");
			add("Glentogher");
			add("Straffan");
			add("Roosky");
		}
	};

	/*
	 * Originally, the team considered doing some work with Legal Towns and
	 * cities. However, it was soon realised that very few garda stations fall
	 * within a legal town or city (approx. 10%), and so the query results
	 * wouldn't be very interesting. Instead, Electoral Divisions were chosen as
	 * a second region to query for crime statistics.
	 */
	public static List<String> ALL_LEGAL_TOWNS_AND_CITIES = new ArrayList<String>() {
		{
			add("Ardee Legal Town");
			add("Arklow Legal Town");
			add("Athlone Legal Town");
			add("Athy Legal Town");
			add("Balbriggan Legal Town");
			add("Ballina Legal Town");
			add("Ballinasloe Legal Town");
			add("Ballybay Legal Town");
			add("Ballyshannon Legal Town");
			add("Bandon Legal Town");
			add("Bantry Legal Town");
			add("Belturbet Legal Town");
			add("Birr Legal Town");
			add("Boyle Legal Town");
			add("Bray Legal Town");
			add("Buncrana Legal Town");
			add("Bundoran Legal Town");
			add("Carlow Legal Town");
			add("Carrick-On-Suir Legal Town");
			add("Carrickmacross Legal Town");
			add("Cashel Legal Town");
			add("Castlebar Legal Town");
			add("Castleblayney Legal Town");
			add("Cavan Legal Town");
			add("Clonakilty Legal Town");
			add("Clones Legal Town");
			add("Clonmel Legal Town");
			add("Cobh Legal Town");
			add("Cootehill Legal Town");
			add("Cork City");
			add("Drogheda Legal Town");
			add("Droichead Nua Legal Town");
			add("Dublin City");
			add("Dundalk Legal Town");
			add("Dungarvan Legal Town");
			add("Edenderry Legal Town");
			add("Ennis Legal Town");
			add("Enniscorthy Legal Town");
			add("Fermoy Legal Town");
			add("Galway City");
			add("Gorey Legal Town");
			add("Granard Legal Town");
			add("Greystones Legal Town");
			add("Kilkee Legal Town");
			add("Kilkenny Legal Town");
			add("Killarney Legal Town");
			add("Kilrush Legal Town");
			add("Kinsale Legal Town");
			add("Leixlip Legal Town");
			add("Letterkenny Legal Town");
			add("Limerick City");
			add("Lismore Legal Town");
			add("Listowel Legal Town");
			add("Longford Legal Town");
			add("Loughrea Legal Town");
			add("Macroom Legal Town");
			add("Mallow Legal Town");
			add("Midleton Legal Town");
			add("Monaghan Legal Town");
			add("Mountmellick Legal Town");
			add("Muinebeag Legal Town");
			add("Mullingar Legal Town");
			add("Naas Legal Town");
			add("Navan (An Uaimh) Legal Town");
			add("Nenagh Legal Town");
			add("New Ross Legal Town");
			add("Passage West Legal Town");
			add("Portlaoighise Legal Town");
			add("Shannon Legal Town");
			add("Skibbereen Legal Town");
			add("Sligo Legal Town");
			add("Templemore Legal Town");
			add("Thurles Legal Town");
			add("Tipperary Legal Town");
			add("Tralee Legal Town");
			add("Tramore Legal Town");
			add("Trim Legal Town");
			add("Tuam Legal Town");
			add("Tullamore Legal Town");
			add("Waterford City");
			add("Westport Legal Town");
			add("Wexford Legal Town");
			add("Wicklow Legal Town");
			add("Youghal Legal Town");
		}
	};

	/*
	 * See note above about 'Legal Towns and Cities'
	 */
	public static void printAllLegalTownsAndCities() {
		System.out.println(GREEN_BOLD + "The legal towns/cities you can select (easiest to just copy+paste): " + RESET);
		for (String townOrCity : ALL_LEGAL_TOWNS_AND_CITIES) {
			System.out.println("\t" + townOrCity);
		}
	}

	public static void printAllElectoralDivisions() {
		System.out
				.println(GREEN_BOLD + "The electoral divisions you can select (easiest to just copy+paste): " + RESET);
		for (String electoralDivision : ALL_ELECTORAL_DIVISIONS) {
			System.out.println("\t" + electoralDivision);
		}
	}

	public static void printAllGardaDivisions() {
		System.out.println(GREEN_BOLD + "The garda divisions you can select (easiest to just copy+paste): " + RESET);
		for (String gardaDivision : ALL_DIVISIONS) {
			System.out.println("\t" + gardaDivision);
		}
	}

}
